// Exact -M50 rename oracle from the reviewed quarry cut.
export const EXTRACTION_MAP = [
  ['glue/bin-executor.ts', 'glue/bin-executor.ts'],
  ['glue/bounded-asset-fetch.fault.test.ts', 'glue/bounded-asset-fetch.fault.test.ts'],
  ['glue/bounded-asset-fetch.ts', 'glue/bounded-asset-fetch.ts'],
  ['glue/child-terminal.test.ts', 'glue/child-terminal.test.ts'],
  ['glue/child-terminal.ts', 'glue/child-terminal.ts'],
  ['glue/dep-snapshot.test.ts', 'glue/dep-snapshot.test.ts'],
  ['glue/dep-snapshot.ts', 'glue/dep-snapshot.ts'],
  ['glue/dev-server-ipc.test.ts', 'glue/dev-server-ipc.test.ts'],
  ['glue/dev-server-ipc.ts', 'glue/dev-server-ipc.ts'],
  ['glue/eddy-learned-pins.test.ts', 'glue/eddy-learned-pins.test.ts'],
  ['glue/eddy-learned-pins.ts', 'glue/eddy-learned-pins.ts'],
  ['glue/starter.fault.test.ts', 'glue/git-initial-baseline.fault.test.ts'],
  ['glue/install-artifact-identity.ts', 'glue/install-artifact-identity.ts'],
  ['glue/install-prefetch.test.ts', 'glue/install-prefetch.test.ts'],
  ['glue/install-prefetch.ts', 'glue/install-prefetch.ts'],
  ['glue/install-stamp-authority.fault.test.ts', 'glue/install-stamp-authority.fault.test.ts'],
  ['glue/install-stamp-authority.test.ts', 'glue/install-stamp-authority.test.ts'],
  ['glue/install-stamp-authority.ts', 'glue/install-stamp-authority.ts'],
  ['glue/install-stamp.test.ts', 'glue/install-stamp.test.ts'],
  ['glue/install-stamp.ts', 'glue/install-stamp.ts'],
  ['glue/npm-shell-command.test.ts', 'glue/npm-shell-command.test.ts'],
  ['glue/npm-shell-command.ts', 'glue/npm-shell-command.ts'],
  ['glue/owner-bridge-key.ts', 'glue/owner-bridge-key.ts'],
  ['glue/owner-sync-runtime-handlers.test.ts', 'glue/owner-sync-runtime-handlers.test.ts'],
  ['glue/owner-vfs-client.test.ts', 'glue/owner-vfs-client.test.ts'],
  ['glue/owner-vfs-client.ts', 'glue/owner-vfs-client.ts'],
  ['glue/owner-vfs-durability.fault.test.ts', 'glue/owner-vfs-durability.fault.test.ts'],
  ['glue/owner-vfs-ipc.test.ts', 'glue/owner-vfs-ipc.test.ts'],
  ['glue/owner-vfs-ipc.ts', 'glue/owner-vfs-ipc.ts'],
  ['glue/owner-vfs-protocol.ts', 'glue/owner-vfs-protocol.ts'],
  ['glue/package-mutation-executor.test.ts', 'glue/package-mutation-executor.test.ts'],
  ['glue/package-mutation-executor.ts', 'glue/package-mutation-executor.ts'],
  ['glue/preview-bridge-wiring.ts', 'glue/preview-bridge-wiring.ts'],
  ['glue/preview-port-wiring.ts', 'glue/preview-port-wiring.ts'],
  ['glue/process-exit.test.ts', 'glue/process-exit.test.ts'],
  ['glue/process-exit.ts', 'glue/process-exit.ts'],
  ['glue/project-deps.test.ts', 'glue/project-deps.test.ts'],
  ['glue/project-deps.ts', 'glue/project-deps.ts'],
  ['glue/project-document.fault.test.ts', 'glue/project-document.fault.test.ts'],
  ['glue/project-document.test.ts', 'glue/project-document.test.ts'],
  ['glue/project-document.ts', 'glue/project-document.ts'],
  ['glue/project-seed-paths.test.ts', 'glue/project-seed-paths.test.ts'],
  ['glue/project-seed-paths.ts', 'glue/project-seed-paths.ts'],
  ['glue/pty-client.test.ts', 'glue/pty-client.test.ts'],
  ['glue/pty-client.ts', 'glue/pty-client.ts'],
  ['glue/pty-protocol.ts', 'glue/pty-protocol.ts'],
  ['glue/reachable-cwd.test.ts', 'glue/reachable-cwd.test.ts'],
  ['glue/reachable-cwd.ts', 'glue/reachable-cwd.ts'],
  ['glue/registry-fetch.test.ts', 'glue/registry-fetch.test.ts'],
  ['glue/registry-fetch.ts', 'glue/registry-fetch.ts'],
  ['glue/run-foreground-child.test.ts', 'glue/run-foreground-child.test.ts'],
  ['glue/run-foreground-child.ts', 'glue/run-foreground-child.ts'],
  ['glue/run-nested-shell-command.test.ts', 'glue/run-nested-shell-command.test.ts'],
  ['glue/run-nested-shell-command.ts', 'glue/run-nested-shell-command.ts'],
  ['glue/scoped-vfs.ts', 'glue/scoped-vfs.test-fixture.ts'],
  ['glue/scoped-vfs.test.ts', 'glue/scoped-vfs.test.ts'],
  ['glue/sqlite-wasm-provider.fault.test.ts', 'glue/sqlite-wasm-provider.fault.test.ts'],
  ['glue/sqlite-wasm-provider.ts', 'glue/sqlite-wasm-provider.ts'],
  ['glue/sync-mirror-vfs.test.ts', 'glue/sync-mirror-vfs.test.ts'],
  ['glue/sync-mirror-vfs.ts', 'glue/sync-mirror-vfs.ts'],
  ['glue/vfs-commit-coordinator.fault.test.ts', 'glue/vfs-commit-coordinator.fault.test.ts'],
  ['glue/vfs-commit-coordinator.test.ts', 'glue/vfs-commit-coordinator.test.ts'],
  ['glue/vfs-commit-coordinator.ts', 'glue/vfs-commit-coordinator.ts'],
  ['glue/vfs-snapshot-port.test.ts', 'glue/vfs-snapshot-port.test.ts'],
  ['glue/vfs-snapshot-port.ts', 'glue/vfs-snapshot-port.ts'],
  ['glue/workspace-archive.test.ts', 'glue/workspace-archive.test.ts'],
  ['glue/workspace-archive.ts', 'glue/workspace-archive.ts'],
  ['workbench/errors.test.ts', 'workbench/errors.test.ts'],
  ['workbench/health.ts', 'workbench/health.ts'],
  [
    'workbench/internal/browser-workbench-composition.ts',
    'workbench/internal/browser-playground-workbench-composition.ts',
  ],
  ['workbench/internal/node-command.ts', 'workbench/internal/node-command.ts'],
  ['workbench/internal/own-property.ts', 'workbench/internal/own-property.ts'],
  [
    'workbench/internal/playground-archive.contract.test.ts',
    'workbench/internal/playground-archive.contract.test.ts',
  ],
  ['workbench/internal/playground-archive.ts', 'workbench/internal/playground-archive.ts'],
  ['workbench/internal/playground-boot-config.ts', 'workbench/internal/playground-boot-config.ts'],
  [
    'workbench/internal/playground-owner-protocol.test.ts',
    'workbench/internal/playground-owner-protocol.test.ts',
  ],
  [
    'workbench/internal/playground-owner-protocol.ts',
    'workbench/internal/playground-owner-protocol.ts',
  ],
  [
    'workbench/internal/playground-preview-registry.contract.test.ts',
    'workbench/internal/playground-preview-registry.contract.test.ts',
  ],
  [
    'workbench/internal/playground-preview-registry.ts',
    'workbench/internal/playground-preview-registry.ts',
  ],
  [
    'workbench/internal/playground-project-catalog.ts',
    'workbench/internal/playground-project-catalog.ts',
  ],
  [
    'workbench/internal/playground-project-definition.ts',
    'workbench/internal/playground-project-definition.ts',
  ],
  [
    'workbench/internal/playground-scm.contract.test.ts',
    'workbench/internal/playground-scm.contract.test.ts',
  ],
  ['workbench/internal/playground-scm.ts', 'workbench/internal/playground-scm.ts'],
  [
    'workbench/internal/playground-session-tool-coordinator.contract.test.ts',
    'workbench/internal/playground-session-tool-coordinator.contract.test.ts',
  ],
  [
    'workbench/internal/playground-session-tool-coordinator.ts',
    'workbench/internal/playground-session-tool-coordinator.ts',
  ],
  [
    'workbench/internal/playground-session-tools-transport.contract.test.ts',
    'workbench/internal/playground-session-tools-transport.contract.test.ts',
  ],
  [
    'workbench/internal/playground-session-tools-transport.ts',
    'workbench/internal/playground-session-tools-transport.ts',
  ],
  [
    'workbench/internal/playground-terminal-state.fault.test.ts',
    'workbench/internal/playground-terminal-state.fault.test.ts',
  ],
  [
    'workbench/internal/playground-terminal-state.ts',
    'workbench/internal/playground-terminal-state.ts',
  ],
  [
    'workbench/internal/playground-typescript.contract.test.ts',
    'workbench/internal/playground-typescript.contract.test.ts',
  ],
  ['workbench/internal/playground-typescript.ts', 'workbench/internal/playground-typescript.ts'],
  [
    'workbench/internal/playground-workbench.contract.test.ts',
    'workbench/internal/playground-workbench.contract.test.ts',
  ],
  ['workbench/internal/playground-workbench.ts', 'workbench/internal/playground-workbench.ts'],
  ['workbench/internal/project-package-config.ts', 'workbench/internal/project-package-config.ts'],
  ['glue/snapshot-fs.test.ts', 'workbench/internal/snapshot-fs.test.ts'],
  ['glue/snapshot-fs.ts', 'workbench/internal/snapshot-fs.ts'],
  ['glue/ts-ls-client.test.ts', 'workbench/internal/typescript-relay-client.test.ts'],
  ['glue/ts-ls-client.ts', 'workbench/internal/typescript-relay-client.ts'],
  [
    'workbench/internal/workbench-health-authority.ts',
    'workbench/internal/workbench-health-authority.ts',
  ],
  ['workbench/node-project-runtime.test.ts', 'workbench/node-project-runtime.test.ts'],
  ['workbench/node-project-runtime.ts', 'workbench/node-project-runtime.ts'],
  ['workbench/open-workbench.contract.test.ts', 'workbench/open-workbench.contract.test.ts'],
  ['workbench/open-workbench.test.ts', 'workbench/open-workbench.test.ts'],
  ['workbench/open-workbench.ts', 'workbench/open-workbench.ts'],
  ['workbench/owner-protocol.test.ts', 'workbench/owner-protocol.test.ts'],
  ['workbench/owner-protocol.ts', 'workbench/owner-protocol.ts'],
  ['workbench/playground.ts', 'workbench/playground.ts'],
  ['workbench/preview-readiness.test.ts', 'workbench/preview-readiness.test.ts'],
  ['workbench/preview-readiness.ts', 'workbench/preview-readiness.ts'],
  [
    'workbench/project-content-owner-mutation-ordering.fault.test.ts',
    'workbench/project-content-owner-mutation-ordering.fault.test.ts',
  ],
  [
    'workbench/project-content-terminal-git-ordering.fault.test.ts',
    'workbench/project-content-terminal-git-ordering.fault.test.ts',
  ],
  ['workbench/project-content-transport.test.ts', 'workbench/project-content-transport.test.ts'],
  ['workbench/project-content-transport.ts', 'workbench/project-content-transport.ts'],
  ['workbench/project-content.contract.test.ts', 'workbench/project-content.contract.test.ts'],
  ['workbench/project-content.test-fixture.ts', 'workbench/project-content.test-fixture.ts'],
  ['workbench/project-content.ts', 'workbench/project-content.ts'],
  ['workbench/project-definition.test.ts', 'workbench/project-definition.test.ts'],
  ['workbench/project-definition.ts', 'workbench/project-definition.ts'],
  [
    'workbench/project-documents-ordering.fault.test.ts',
    'workbench/project-documents-ordering.fault.test.ts',
  ],
  ['workbench/project-documents.contract.test.ts', 'workbench/project-documents.contract.test.ts'],
  ['workbench/project-documents.ts', 'workbench/project-documents.ts'],
  ['workbench/project-file-boundary.ts', 'workbench/project-file-boundary.ts'],
  ['workbench/project-files.contract.test.ts', 'workbench/project-files.contract.test.ts'],
  ['workbench/project-files.ts', 'workbench/project-files.ts'],
  [
    'workbench/project-materialization.fault.test.ts',
    'workbench/project-materialization.fault.test.ts',
  ],
  ['workbench/project-materialization.ts', 'workbench/project-materialization.ts'],
  ['workbench/project-session.test.ts', 'workbench/project-session.test.ts'],
  ['workbench/project-session.ts', 'workbench/project-session.ts'],
  ['workbench/project-terminal-state.ts', 'workbench/project-terminal-state.ts'],
  ['workbench/project-terminal.test.ts', 'workbench/project-terminal.test.ts'],
  ['workbench/project-terminal.ts', 'workbench/project-terminal.ts'],
  ['workbench/project-vfs-protocol.ts', 'workbench/project-vfs-protocol.ts'],
  ['workbench/public.ts', 'workbench/public.ts'],
  ['workbench/service-worker-control.test.ts', 'workbench/service-worker-control.test.ts'],
  ['workbench/service-worker-control.ts', 'workbench/service-worker-control.ts'],
  ['workbench/vite-project-runtime.test.ts', 'workbench/vite-project-runtime.test.ts'],
  ['workbench/vite-project-runtime.ts', 'workbench/vite-project-runtime.ts'],
  ['workbench/workbench-browser-owner.test.ts', 'workbench/workbench-browser-owner.test.ts'],
  ['workbench/workbench-browser-owner.ts', 'workbench/workbench-browser-owner.ts'],
  [
    'workbench/workbench-health-authority.contract.test.ts',
    'workbench/workbench-health-authority.contract.test.ts',
  ],
  ['workbench/workbench-owner-port.test.ts', 'workbench/workbench-owner-port.test.ts'],
  ['workbench/workbench-owner-port.ts', 'workbench/workbench-owner-port.ts'],
  ['workers/bundle-local-buffer.test.ts', 'workers/bundle-local-buffer.test.ts'],
  ['workers/dev-boot-clean.test.ts', 'workers/dev-boot-clean.test.ts'],
  ['workers/dev-boot-clean.ts', 'workers/dev-boot-clean.ts'],
  ['workers/dev-server-boot.test.ts', 'workers/dev-server-boot.test.ts'],
  ['workers/dev-server-boot.ts', 'workers/dev-server-boot.ts'],
  ['workers/dev-server-child-bootstrap.ts', 'workers/dev-server-child-bootstrap.ts'],
  ['workers/dev-server-child-config.test.ts', 'workers/dev-server-child-config.test.ts'],
  ['workers/dev-server-child-config.ts', 'workers/dev-server-child-config.ts'],
  ['workers/dev-server-controller.test.ts', 'workers/dev-server-controller.test.ts'],
  ['workers/dev-server-controller.ts', 'workers/dev-server-controller.ts'],
  ['workers/esbuild-runtime-fs.test.ts', 'workers/esbuild-runtime-fs.test.ts'],
  ['workers/esbuild-runtime-fs.ts', 'workers/esbuild-runtime-fs.ts'],
  ['workers/generated/esbuild-runtime.js', 'workers/generated/esbuild-runtime.js'],
  ['workers/kernel-worker-entry.test.ts', 'workers/kernel-worker-entry.test.ts'],
  ['workers/kernel-worker-entry.ts', 'workers/kernel-worker-entry.ts'],
  ['workers/node-entry-bootstrap.test.ts', 'workers/node-entry-bootstrap.test.ts'],
  ['workers/node-entry-bootstrap.ts', 'workers/node-entry-bootstrap.ts'],
  ['workers/node-entry-remote-fs.test.ts', 'workers/node-entry-remote-fs.test.ts'],
  ['workers/node-entry-remote-fs.ts', 'workers/node-entry-remote-fs.ts'],
  ['workers/node-entry-resolve.test.ts', 'workers/node-entry-resolve.test.ts'],
  ['workers/node-entry-resolve.ts', 'workers/node-entry-resolve.ts'],
  ['workers/node-program-lifecycle.test.ts', 'workers/node-program-lifecycle.test.ts'],
  ['workers/node-program-lifecycle.ts', 'workers/node-program-lifecycle.ts'],
  ['workers/node-worker-runtime-config.ts', 'workers/node-worker-runtime-config.ts'],
  ['workers/owner-child-bin-executor.test.ts', 'workers/owner-child-bin-executor.test.ts'],
  ['workers/owner-child-dev-server.test.ts', 'workers/owner-child-dev-server.test.ts'],
  ['workers/owner-child-node-executor.test.ts', 'workers/owner-child-node-executor.test.ts'],
  ['workers/owner-child-node-executor.ts', 'workers/owner-child-node-executor.ts'],
  ['workers/owner-package-ingress.test.ts', 'workers/owner-package-ingress.test.ts'],
  ['workers/owner-package-state.test.ts', 'workers/owner-package-state.test.ts'],
  ['workers/owner-package-state.ts', 'workers/owner-package-state.ts'],
  ['workers/owner-storage.test.ts', 'workers/owner-storage.test.ts'],
  ['workers/owner-storage.ts', 'workers/owner-storage.ts'],
  ['workers/owner-vfs-applied-journal.ts', 'workers/owner-vfs-applied-journal.ts'],
  ['workers/owner-vfs-authority.fault.test.ts', 'workers/owner-vfs-authority.fault.test.ts'],
  ['workers/owner-vfs-authority.test.ts', 'workers/owner-vfs-authority.test.ts'],
  ['workers/owner-vfs-authority.ts', 'workers/owner-vfs-authority.ts'],
  [
    'workers/package-acquisition-authority.fault.test.ts',
    'workers/package-acquisition-authority.fault.test.ts',
  ],
  [
    'workers/package-acquisition-authority.test.ts',
    'workers/package-acquisition-authority.test.ts',
  ],
  ['workers/package-acquisition-authority.ts', 'workers/package-acquisition-authority.ts'],
  [
    'workers/package-acquisition-invalid-claim.test.ts',
    'workers/package-acquisition-invalid-claim.test.ts',
  ],
  ['workers/package-install-finalizer.test.ts', 'workers/package-install-finalizer.test.ts'],
  [
    'workers/playground-archive-integration.contract.test.ts',
    'workers/playground-archive-integration.contract.test.ts',
  ],
  ['workers/playground-archive-integration.ts', 'workers/playground-archive-integration.ts'],
  [
    'workers/playground-legacy-catalog-migration.fault.test.ts',
    'workers/playground-legacy-catalog-migration.fault.test.ts',
  ],
  ['workers/playground-project-authority.ts', 'workers/playground-project-authority.ts'],
  [
    'workers/playground-project-catalog.contract.test.ts',
    'workers/playground-project-catalog.contract.test.ts',
  ],
  [
    'workers/playground-session-tools-owner.contract.test.ts',
    'workers/playground-session-tools-owner.contract.test.ts',
  ],
  ['workers/playground-session-tools-owner.ts', 'workers/playground-session-tools-owner.ts'],
  ['workers/port-watch.test.ts', 'workers/port-watch.test.ts'],
  ['workers/port-watch.ts', 'workers/port-watch.ts'],
  ['workers/preview-producer-bindings.test.ts', 'workers/preview-producer-bindings.test.ts'],
  ['workers/preview-producer-bindings.ts', 'workers/preview-producer-bindings.ts'],
  ['workers/preview-registry.test.ts', 'workers/preview-registry.test.ts'],
  ['workers/preview-registry.ts', 'workers/preview-registry.ts'],
  ['workers/project-terminal-namespace.test.ts', 'workers/project-terminal-namespace.test.ts'],
  ['workers/project-terminal-namespace.ts', 'workers/project-terminal-namespace.ts'],
  ['workers/pty-server.test.ts', 'workers/pty-server.test.ts'],
  ['workers/pty-server.ts', 'workers/pty-server.ts'],
  ['workers/test-fixtures/durable-owner-fs.ts', 'workers/test-fixtures/durable-owner-fs.ts'],
  ['workers/ts-lsp-owner-relay.contract.test.ts', 'workers/ts-lsp-owner-relay.contract.test.ts'],
  ['workers/ts-lsp-owner-relay.ts', 'workers/ts-lsp-owner-relay.ts'],
  ['workers/ts-lsp-worker-entry.ts', 'workers/ts-lsp-worker-entry.ts'],
  ['workers/vite-cli-install-policy.ts', 'workers/vite-cli-install-policy.ts'],
  ['workers/vite-cli-prep.test.ts', 'workers/vite-cli-prep.test.ts'],
  ['workers/vite-cli-prep.ts', 'workers/vite-cli-prep.ts'],
  ['workers/vite-esbuild-runtime.ts', 'workers/vite-esbuild-runtime.ts'],
  [
    'workers/workbench-first-materialization.contract.test.ts',
    'workers/workbench-first-materialization.contract.test.ts',
  ],
  ['workers/workbench-owner-child-vfs.ts', 'workers/workbench-owner-child-vfs.ts'],
  ['workers/workbench-owner-controller.test.ts', 'workers/workbench-owner-controller.test.ts'],
  ['workers/workbench-owner-controller.ts', 'workers/workbench-owner-controller.ts'],
  ['workers/workbench-package-config.test.ts', 'workers/workbench-package-config.test.ts'],
  ['workers/workbench-package-config.ts', 'workers/workbench-package-config.ts'],
  [
    'workers/workbench-project-composition.test.ts',
    'workers/workbench-project-composition.test.ts',
  ],
  ['workers/workbench-project-composition.ts', 'workers/workbench-project-composition.ts'],
  ['workers/workbench-project-runtime.test.ts', 'workers/workbench-project-runtime.test.ts'],
  ['workers/workbench-project-runtime.ts', 'workers/workbench-project-runtime.ts'],
  ['workers/workbench-project-store.test.ts', 'workers/workbench-project-store.test.ts'],
  ['workers/workbench-project-store.ts', 'workers/workbench-project-store.ts'],
  ['workers/workbench-project-vfs.test.ts', 'workers/workbench-project-vfs.test.ts'],
  ['workers/workbench-project-vfs.ts', 'workers/workbench-project-vfs.ts'],
  ['workers/worker-runtime-globals.ts', 'workers/worker-runtime-globals.ts'],
] as const;
