import {
  type GitIdentity,
  type LogEntry,
  makeGit,
  requireSupportedStatusEntries,
  vfsToGitFs,
} from '@riftydev/git';
import type { Vfs } from '@riftydev/vfs';

const INITIAL_COMMIT_MESSAGE = 'Initial commit';
const GENERATED_BASELINE_FILE = 'package-lock.json';
const STARTER_HEAD = 'ref: refs/heads/main\n';
const STARTER_MAIN_REF = 'refs/heads/main';

function initialCommitAuthor(): GitIdentity {
  return {
    name: 'rifty',
    email: 'rifty@localhost',
    timestamp: Math.floor(Date.now() / 1000),
    timezoneOffset: 0,
  };
}

async function starterHeadOid(
  vfs: Vfs,
  root: string,
  g: ReturnType<typeof makeGit>,
): Promise<string | null> {
  const head = await vfs.readFileText(`${root}/.git/HEAD`);
  if (head === STARTER_HEAD) {
    const looseRef = `${root}/.git/${STARTER_MAIN_REF}`;
    if (await vfs.exists(looseRef)) {
      await vfs.readFile(looseRef);
    } else {
      const packedRefs = `${root}/.git/packed-refs`;
      if (!(await vfs.exists(packedRefs))) return null;
      await vfs.readFile(packedRefs);
    }
  }
  return g.resolveRef('HEAD');
}

async function preflightLooseObjectRead(vfs: Vfs, root: string, oid: string): Promise<void> {
  const path = `${root}/.git/objects/${oid.slice(0, 2)}/${oid.slice(2)}`;
  if (await vfs.exists(path)) await vfs.readFile(path);
}

function isInsideNodeModules(filepath: string): boolean {
  return filepath.split('/').slice(0, -1).includes('node_modules');
}

async function resetInterruptedStarterIndex(vfs: Vfs, root: string): Promise<void> {
  // No HEAD means this index is baseline scratch, possibly torn by an earlier open.
  await vfs.rm(`${root}/.git/index`, { force: true });
}

async function stageInitialTree(g: ReturnType<typeof makeGit>): Promise<boolean> {
  const changed = requireSupportedStatusEntries(
    (await g.status()).filter((entry) => !isInsideNodeModules(entry.filepath)),
  );
  for (const entry of changed) {
    if (entry.status === '111') continue;
    if (entry.status === '101' || entry.status === '100') await g.remove(entry.filepath);
    else await g.add(entry.filepath);
  }
  return changed.some((entry) => entry.status !== '111');
}

function isRiftyInitialIdentity(identity: GitIdentity): boolean {
  return (
    identity.name === 'rifty' &&
    identity.email === 'rifty@localhost' &&
    identity.timezoneOffset === 0
  );
}

async function matchingRiftyInitialCommit(
  vfs: Vfs,
  root: string,
  g: ReturnType<typeof makeGit>,
  expectedOid: string,
): Promise<LogEntry | null> {
  await preflightLooseObjectRead(vfs, root, expectedOid);
  const log = await g.log({ depth: 2 });
  const commit = log[0];
  if (
    log.length !== 1 ||
    commit === undefined ||
    commit.oid !== expectedOid ||
    commit.parents.length !== 0 ||
    commit.message.trim() !== INITIAL_COMMIT_MESSAGE ||
    !isRiftyInitialIdentity(commit.author) ||
    !isRiftyInitialIdentity(commit.committer)
  ) {
    return null;
  }
  return commit;
}

function isPackageManifest(filepath: string): boolean {
  return filepath.split('/').at(-1) === 'package.json' && !isInsideNodeModules(filepath);
}

async function generatedBaselineBlobOid(
  vfs: Vfs,
  root: string,
  g: ReturnType<typeof makeGit>,
  treeOid: string,
): Promise<string | null> {
  await preflightLooseObjectRead(vfs, root, treeOid);
  const shown = await g.show(treeOid);
  if (shown.type !== 'tree') throw new Error('Starter baseline tree OID did not resolve to a tree');
  const entry = shown.entries.find(({ path }) => path === GENERATED_BASELINE_FILE);
  if (entry === undefined) return null;
  if (entry.type !== 'blob') throw new Error('Starter baseline package-lock.json is not a blob');
  return entry.oid;
}

/**
 * Make a freshly-seeded Starter look like a normal project checkout: one real
 * root commit on `main`; ignored files and dependency trees stay outside it.
 */
export async function ensureStarterInitialCommit(vfs: Vfs, root: string): Promise<string | null> {
  const g = makeGit({ fs: vfsToGitFs(vfs), dir: root });
  if (!(await vfs.exists(`${root}/.git/HEAD`))) await g.init();
  if ((await starterHeadOid(vfs, root, g)) !== null) return null;
  await resetInterruptedStarterIndex(vfs, root);

  const hasChanges = await stageInitialTree(g);
  if (!hasChanges) return null;

  const author = initialCommitAuthor();
  return g.commit({ message: INITIAL_COMMIT_MESSAGE, author, committer: author });
}

/**
 * Fold the exact lock generated by the first bare install into the untouched
 * Starter root. Any user branch, staged state, or workspace-manifest drift
 * leaves the lock visible.
 */
export async function amendStarterGeneratedBaseline(
  vfs: Vfs,
  root: string,
  expectedInitialOid: string,
  lockfile: Uint8Array,
): Promise<boolean> {
  const g = makeGit({ fs: vfsToGitFs(vfs), dir: root });
  if ((await g.currentBranch()) !== 'main') return false;
  if ((await starterHeadOid(vfs, root, g)) !== expectedInitialOid) return false;

  const initial = await matchingRiftyInitialCommit(vfs, root, g, expectedInitialOid);
  if (initial === null) return false;

  const expectedLockOid = await g.hashBlob(lockfile);
  const lockPath = `${root}/${GENERATED_BASELINE_FILE}`;
  if (
    !(await vfs.exists(lockPath)) ||
    (await g.hashBlob(await vfs.readFile(lockPath))) !== expectedLockOid ||
    (await generatedBaselineBlobOid(vfs, root, g, initial.tree)) !== null
  ) {
    return false;
  }

  const status = requireSupportedStatusEntries(await g.status());
  if (
    status.some((entry) => entry.status[0] !== entry.status[2]) ||
    status.some((entry) => isPackageManifest(entry.filepath) && entry.status !== '111')
  ) {
    return false;
  }

  await g.add(GENERATED_BASELINE_FILE);
  const finalOid = await g.commit({
    message: INITIAL_COMMIT_MESSAGE,
    author: initial.author,
    committer: initial.committer,
    amend: true,
  });
  const final = await matchingRiftyInitialCommit(vfs, root, g, finalOid);
  const finalLockOid =
    final === null ? null : await generatedBaselineBlobOid(vfs, root, g, final.tree);
  const delta = await g.diff({ kind: 'refs', oldRef: initial.oid, newRef: finalOid });
  if (
    final?.oid !== finalOid ||
    finalLockOid !== expectedLockOid ||
    delta.length !== 1 ||
    delta[0]?.filepath !== GENERATED_BASELINE_FILE ||
    delta[0].change !== 'add'
  ) {
    throw new Error('Starter generated baseline amend violated its exact Git contract');
  }
  return true;
}

/**
 * Bind first-install finalization to its exact Starter root: consume the
 * recorded initial OID once, amend, then settle durability. Declines skip the
 * flush; a rejected flush propagates loud after the in-memory amend landed.
 */
export function createStarterBaselineFinalizer(
  vfs: Vfs,
  starterInitialOids: Map<string, string>,
  settleDurability: () => Promise<void>,
): (root: string, lockfile: Uint8Array) => Promise<boolean> {
  return async (root, lockfile) => {
    const expectedInitialOid = starterInitialOids.get(root);
    starterInitialOids.delete(root);
    if (expectedInitialOid === undefined) return false;
    if (!(await amendStarterGeneratedBaseline(vfs, root, expectedInitialOid, lockfile))) {
      return false;
    }
    await settleDurability();
    return true;
  };
}
