import { defineConfig } from 'tsup';

// Generated by tools/publishing/sync-publish-config.mjs (ADR-0070). Do not edit by hand.
// Bundles each public entry to ESM + a bundled .d.ts in dist/. First-party
// @riftydev/* and declared external deps stay external (not double-bundled).
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'esbuild-transform': 'src/esbuild-transform.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'es2022',
  external: [/^@riftydev\//],
});
