import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { withNodeContractWorkspace } from './esbuild-contract-node-workspace.ts';
import {
  type EsbuildContractApi,
  type EsbuildContractTranscript,
  type EsbuildGuestPolicyTranscript,
  probeEsbuildContract,
  probeEsbuildGuestPolicy,
} from './esbuild-contract-probe.ts';
import fixture from './fixtures/esbuild-0.28.0-contract.json';
import policyFixture from './fixtures/esbuild-0.28.0-guest-policy-prerequisites.json';

const expected = fixture as unknown as EsbuildContractTranscript;
const expectedPolicy = policyFixture as unknown as EsbuildGuestPolicyTranscript;
const require = createRequire(import.meta.url);

describe('esbuild 0.28.0 Vite contract oracle', () => {
  it('the checked row transcript is regenerated by the exact native package', async () => {
    const cjs = require('esbuild') as EsbuildContractApi;
    const specifier = 'esbuild';
    const esm = (await import(specifier)) as Readonly<Record<string, unknown>>;
    const esmAgain = (await import(specifier)) as Readonly<Record<string, unknown>>;
    const mainPath = require.resolve('esbuild');
    const moduleIdentity = JSON.parse(
      execFileSync(
        process.execPath,
        [
          '--input-type=module',
          '-e',
          `import { createRequire } from 'node:module'; import { pathToFileURL } from 'node:url'; const p = process.argv[1]; const c = createRequire(import.meta.url)(p); const e = await import(pathToFileURL(p).href); process.stdout.write(JSON.stringify({ esmDefaultIsCjsOuter: e.default === c }));`,
          mainPath,
        ],
        { encoding: 'utf8' },
      ),
    ) as { readonly esmDefaultIsCjsOuter: boolean };
    expect(cjs.version).toBe('0.28.0');
    const modules = {
      cjs,
      esm,
      ...moduleIdentity,
      esmNamespaceStable: esmAgain === esm,
    };
    try {
      const runProbe = async (workspace: Parameters<typeof probeEsbuildContract>[1]) => ({
        contract: await probeEsbuildContract(modules, workspace),
        policy: await probeEsbuildGuestPolicy(modules, workspace),
      });
      const actual = await withNodeContractWorkspace(runProbe, {
        baseDirectory: process.cwd(),
      });
      const differentTopology = await withNodeContractWorkspace(runProbe, {
        baseDirectory: process.cwd(),
        rootSuffix: 'nested/deeper/a-deliberately-much-longer-contract-workspace-root',
      });
      const outsideRepoTopology = await withNodeContractWorkspace(runProbe, {
        baseDirectory: tmpdir(),
      });
      expect(differentTopology).toEqual(actual);
      expect(outsideRepoTopology).toEqual(actual);
      if (process.env.RIFTY_PRINT_ESBUILD_CONTRACT === '1') {
        console.log(
          `ESBUILD_CONTRACT_FIXTURE\n${JSON.stringify(actual.contract, null, 2)}\nEND_ESBUILD_CONTRACT_FIXTURE`,
        );
        console.log(
          `ESBUILD_GUEST_POLICY_PREREQUISITES_FIXTURE\n${JSON.stringify(actual.policy, null, 2)}\nEND_ESBUILD_GUEST_POLICY_PREREQUISITES_FIXTURE`,
        );
        return;
      }
      expect(actual.contract).toEqual(expected);
      expect(actual.policy).toEqual(expectedPolicy);
    } finally {
      await cjs.stop();
    }
  });
});
