/**
 * Public surface of `@riftydev/ts-language-service`: a real `ts.LanguageService`
 * driven over the rifty VFS, exposing diagnostics as LSP shapes (ADR-0166).
 *
 * Internal modules (host, overlay, tsconfig, lib-dts, position, vfs-ts-host)
 * are NOT exported — only the service factory and the LSP wire types.
 */

export { createTsLanguageService } from './service.ts';
export type { CreateTsLanguageServiceDeps, TsLanguageService } from './service.ts';
export {
  CompletionItemKind,
  DiagnosticSeverity,
  DocumentHighlightKind,
  SymbolKind,
} from './lsp-types.ts';
export type {
  CallHierarchyIncomingCall,
  CallHierarchyItem,
  CallHierarchyOutgoingCall,
  ClassifiedSpan,
  ClassificationFormat,
  CodeAction,
  CodeFixOptions,
  CloneSafePrimitive,
  CloneSafeValue,
  CombinedCodeFixOptions,
  CompletionDetailsOptions,
  CompletionItem,
  CompletionList,
  CompletionOptions,
  CompletionTriggerCharacter,
  CompletionTriggerKind,
  DefinitionLinks,
  Diagnostic,
  DocCommentTemplateOptions,
  DocumentHighlight,
  DocumentSymbol,
  EmitOutput,
  EmitOutputFile,
  EncodedClassifications,
  FileRenameEditsOptions,
  FoldingRange,
  FormattingOptions,
  Hover,
  InlayHint,
  InlayHintOptions,
  LinkedEditingRanges,
  Location,
  LocationLink,
  MarkupContent,
  MoveToRefactoringFileSuggestions,
  NavigationBarItem,
  OrganizeImportsOptions,
  ParameterInformation,
  PasteEditsOptions,
  Position,
  PrepareRenameResult,
  QuickInfoOptions,
  Range,
  ReferenceContext,
  RefactorEditOptions,
  RefactorOptions,
  RefactorTriggerReason,
  RenameOptions,
  SelectionRange,
  SignatureHelp,
  SignatureHelpOptions,
  SignatureHelpRetriggerCharacter,
  SignatureHelpTriggerCharacter,
  SignatureHelpTriggerReason,
  SignatureInformation,
  SymbolInformation,
  TextEdit,
  TextInsertion,
  TodoComment,
  TodoCommentDescriptor,
  TypeScriptFormatCodeSettings,
  TypeScriptUserPreferences,
  WorkspaceEdit,
  WorkspaceSymbolOptions,
} from './lsp-types.ts';

// Worker hosting (ADR-0166): the page editor + the M12 agent reach ONE shared
// service instance running in a kernel `serve` worker that reads the
// authoritative VFS over the fs.* sync-RPC seam. The Node-proven units (RPC
// FsSync adapter + protocol + endpoint) are public; the side-effectful boot is
// referenced separately (the `./worker/entry` subpath / by URL).
export { createRpcFsSync } from './worker/host-fs-rpc.ts';
export type { SyncBinaryCall, SyncCall } from './worker/host-fs-rpc.ts';
export { createServiceEndpoint } from './worker/service-endpoint.ts';
export type { ServiceEndpoint, ServiceEndpointDeps } from './worker/service-endpoint.ts';
export {
  TS_IPC_TYPE,
  isTsRequestMessage,
  isTsResponseMessage,
} from './worker/protocol.ts';
export type {
  TsRequest,
  TsRequestType,
  TsRequestMessage,
  TsResponse,
  TsResponseMessage,
  TsInitRequest,
  TsOpenRequest,
  TsUpdateRequest,
  TsCloseRequest,
  TsInvalidateRequest,
  TsCleanupSemanticCacheRequest,
  TsSemanticRequest,
  TsSyntacticRequest,
  TsConfigDiagnosticsRequest,
  TsQuickInfoRequest,
  TsDefinitionRequest,
  TsTypeDefinitionRequest,
  TsCompletionsRequest,
  TsCompletionDetailsRequest,
  TsReferencesRequest,
  TsReferencesAtPositionRequest,
  TsPrepareRenameRequest,
  TsRenameEditsRequest,
  TsSignatureHelpRequest,
  TsNameOrDottedNameSpanRequest,
  TsBreakpointStatementRequest,
  TsCodeFixesRequest,
  TsOrganizeImportsRequest,
  TsFormattingEditsRequest,
  TsRangeFormattingEditsRequest,
  TsSuggestionDiagnosticsRequest,
  TsCompilerOptionsDiagnosticsRequest,
  TsImplementationRequest,
  TsDefinitionLinksRequest,
  TsDocumentSymbolsRequest,
  TsNavigationBarItemsRequest,
  TsFoldingRangesRequest,
  TsWorkspaceSymbolsRequest,
  TsInlayHintsRequest,
  TsDocumentHighlightsRequest,
  TsClassificationsRequest,
  TsEncodedClassificationsRequest,
  TsCallHierarchyRequest,
  TsOnTypeFormattingEditsRequest,
  TsBraceMatchingRequest,
  TsIndentationRequest,
  TsValidBraceCompletionRequest,
  TsSpanOfEnclosingCommentRequest,
  TsLineColumnOffsetRequest,
  TsCommentEditsRequest,
  TsRefactorActionsRequest,
  TsRefactorEditsRequest,
  TsMoveToRefactoringFileSuggestionsRequest,
  TsCombinedCodeFixRequest,
  TsFileRenameEditsRequest,
  TsEmitOutputRequest,
  TsSupportedCodeFixesRequest,
  TsApplyCodeActionCommandRequest,
  TsCompletionEntrySymbolRequest,
  TsGetProgramRequest,
  TsSelectionRangeRequest,
  TsFileReferencesRequest,
  TsJsxClosingTagRequest,
  TsLinkedEditingRangeRequest,
  TsDocCommentTemplateRequest,
  TsTodoCommentsRequest,
  TsPreparePasteEditsRequest,
  TsPasteEditsRequest,
  TsDisposeRequest,
  TsAckResponse,
  TsDiagnosticsResponse,
  TsHoverResponse,
  TsLocationsResponse,
  TsCompletionsResponse,
  TsCompletionItemResponse,
  TsPrepareRenameResponse,
  TsWorkspaceEditResponse,
  TsSignatureHelpResponse,
  TsCodeActionsResponse,
  TsTextEditsResponse,
  TsRangeResponse,
  TsRangesResponse,
  TsDefinitionLinksResponse,
  TsDocumentSymbolsResponse,
  TsNavigationBarItemsResponse,
  TsFoldingRangesResponse,
  TsWorkspaceSymbolsResponse,
  TsInlayHintsResponse,
  TsDocumentHighlightsResponse,
  TsClassificationsResponse,
  TsClassifiedSpansResponse,
  TsCallHierarchyItemsResponse,
  TsIncomingCallsResponse,
  TsOutgoingCallsResponse,
  TsIndentationResponse,
  TsBooleanResponse,
  TsPositionResponse,
  TsMoveToRefactoringFileSuggestionsResponse,
  TsEmitOutputResponse,
  TsSupportedCodeFixesResponse,
  TsSelectionRangeResponse,
  TsJsxClosingTagResponse,
  TsLinkedEditingRangeResponse,
  TsTextInsertionResponse,
  TsTodoCommentsResponse,
  TsPreparePasteEditsResponse,
  TsErrorResponse,
} from './worker/protocol.ts';
