import { defineConfig } from 'tsup';

// Generated by tools/publishing/sync-publish-config.mjs (ADR-0070). Do not edit by hand.
// Bundles each public entry to ESM + a bundled .d.ts in dist/. First-party
// @riftydev/* and declared external deps stay external (not double-bundled).
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    protocol: 'src/worker/protocol.ts',
    'lsp-types': 'src/lsp-types.ts',
    'worker/entry': 'src/worker/entry.ts',
    'vendor/lib-bundle.json': 'vendor/lib-bundle.json',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'es2022',
  external: [/^@riftydev\//],
});
