/**
 * WASI smoke. We synthesise a tiny module (using JS-generated bytes via
 * `WebAssembly`-side helpers isn't trivial without external tools), so we
 * test the shim surface directly: a fake host that drives the imports and
 * verifies the syscall responses. Real-binary integration arrives once we
 * vendor hello.wasm/esbuild.wasm.
 */
import { describe, expect, it } from 'vitest';
import { Wasi } from '../../../packages/runtime-wasi/src/wasi.ts';

function makeMemory(): WebAssembly.Memory {
  return new WebAssembly.Memory({ initial: 1 });
}

describe('WASI preview1 shim', () => {
  it('constructs and exposes wasi_snapshot_preview1 imports', () => {
    const wasi = new Wasi({ args: ['a', 'b'] });
    expect(wasi.imports.wasi_snapshot_preview1).toBeDefined();
    const ns = wasi.imports.wasi_snapshot_preview1 as WebAssembly.ModuleImports;
    expect(typeof ns.args_get).toBe('function');
    expect(typeof ns.fd_write).toBe('function');
    expect(typeof ns.proc_exit).toBe('function');
  });

  it('args_sizes_get reports correct count and total size', () => {
    const wasi = new Wasi({ args: ['hello', 'world'] });
    const memory = makeMemory();
    // Manually attach memory by faking start() partial.
    (wasi as unknown as { memory: WebAssembly.Memory }).memory = memory;
    const view = new DataView(memory.buffer);
    const ns = wasi.imports.wasi_snapshot_preview1 as Record<string, (...a: number[]) => number>;
    expect(ns.args_sizes_get?.(0, 4)).toBe(0);
    expect(view.getUint32(0, true)).toBe(2);
    expect(view.getUint32(4, true)).toBe('hello\0world\0'.length);
  });

  it('fd_write to stdout collects bytes through Wasi', () => {
    const wasi = new Wasi();
    const memory = makeMemory();
    (wasi as unknown as { memory: WebAssembly.Memory }).memory = memory;
    const bytes = new Uint8Array(memory.buffer);
    const view = new DataView(memory.buffer);
    const enc = new TextEncoder();
    const data = enc.encode('hi from wasi\n');
    bytes.set(data, 100); // payload at 100
    view.setUint32(8, 100, true); // iov.ptr
    view.setUint32(12, data.length, true); // iov.len
    const ns = wasi.imports.wasi_snapshot_preview1 as Record<string, (...a: number[]) => number>;
    expect(ns.fd_write?.(1, 8, 1, 200)).toBe(0);
    expect(view.getUint32(200, true)).toBe(data.length);
    expect(wasi.collectedStdout()).toBe('hi from wasi\n');
  });

  it('proc_exit throws WasiExit with the code', () => {
    const wasi = new Wasi();
    (wasi as unknown as { memory: WebAssembly.Memory }).memory = makeMemory();
    const ns = wasi.imports.wasi_snapshot_preview1 as Record<string, (...a: number[]) => number>;
    expect(() => ns.proc_exit?.(42)).toThrow(/proc_exit.42/);
  });
});
