import { defineConfig } from 'tsup';

// Generated by tools/publishing/sync-publish-config.mjs (ADR-0070). Do not edit by hand.
// Bundles each public entry to ESM + a bundled .d.ts in dist/. First-party
// @riftydev/* and declared external deps stay external (not double-bundled).
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    worker: 'src/worker-entry.ts',
    'install-process': 'src/ipc/install-process.ts',
    'ipc/exec-sync-handler': 'src/ipc/exec-sync-handler.ts',
    loader: 'src/module-loader/index.ts',
    'env/capabilities': 'src/env/capabilities.ts',
    builtins: 'src/builtins/public.ts',
    'builtins/fs-watch': 'src/builtins/fs-watch.ts',
    'builtins/process': 'src/builtins/process.ts',
    'builtins/timers': 'src/builtins/timers.ts',
    'builtins/buffer': 'src/builtins/buffer.ts',
    'builtins/console': 'src/builtins/console.ts',
    'builtins/module': 'src/builtins/module.ts',
    'builtins/child_process': 'src/builtins/child_process.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'es2022',
  external: [/^@riftydev\//],
});
