import { readFileSync } from 'node:fs';
import { expect, it } from 'vitest';

interface AgentPackageManifest {
  readonly private?: boolean;
  readonly license?: string;
  readonly sideEffects?: boolean;
  readonly files?: readonly string[];
  readonly publishConfig?: {
    readonly access?: string;
    readonly exports?: Record<string, unknown>;
  };
}

it('is generated as a public root-only package', () => {
  const manifest = JSON.parse(
    readFileSync(new URL('../package.json', import.meta.url), 'utf8'),
  ) as AgentPackageManifest;
  expect(manifest.private).not.toBe(true);
  expect(manifest.license).toBe('MIT');
  expect(manifest.sideEffects).toBe(false);
  expect(manifest.files).toEqual(expect.arrayContaining(['dist', 'CHANGELOG.md']));
  expect(manifest.publishConfig?.access).toBe('public');
  expect(Object.keys(manifest.publishConfig?.exports ?? {})).toEqual(['.']);
  expect(readFileSync(new URL('../tsup.config.ts', import.meta.url), 'utf8')).toContain(
    'Generated by tools/publishing/sync-publish-config.mjs',
  );
});
