import { defineConfig } from 'tsup';

// Generated by tools/publishing/sync-publish-config.mjs (ADR-0070). Do not edit by hand.
// Bundles each public entry to ESM + a bundled .d.ts in dist/. First-party
// @rifty/* and declared external deps stay external (not double-bundled).
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    registry: 'src/registry.ts',
    'register-builtins': 'src/register-builtins.ts',
    https: 'src/https.ts',
    'sqlite/engine': 'src/sqlite/engine.ts',
    'sqlite/database-sync': 'src/sqlite/database-sync.ts',
    'sqlite/register-builtins': 'src/sqlite/register-builtins.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'es2022',
  external: [/^@rifty\//],
});
