#!/usr/bin/env node
/**
 * Deterministic public compat matrix generator.
 *
 * This intentionally uses static inventories tied to checked-in conformance
 * and parity files. A Vitest JSON reporter sink can replace the static rows
 * later, but milestone close needs stable public claim pages now.
 * TODO(backlog: toolchain-build/compat-matrix-test-result-sink)
 */
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises';

const here = new URL('.', import.meta.url);
const conformanceDir = new URL('../../tests/conformance/', here);
const matrixDir = new URL('../../docs/public/compat/', here);
const rootDir = new URL('../../', here);

const legend =
  'Legend: ✅ implemented and tested · ⚠️ partial / known caveat · ❌ not implemented (throws `NotImplementedError` or `UNSUPPORTED_PROTOCOL`).';

const generatedNote =
  'Generated by `pnpm compat:generate` from static inventories backed by conformance and parity tests.';

const matrices = [
  {
    file: 'fs.md',
    title: 'Compatibility matrix — `node:fs`',
    intro:
      'Public claim surface for the runtime-local `node:fs` subset over rifty VFS. Rows cite existing conformance and node-parity coverage.',
    rows: [
      [
        '`readFileSync` / `writeFileSync`',
        '✅',
        'utf8 strings and binary `Uint8Array`/Buffer-like reads',
      ],
      ['`mkdirSync({ recursive })`', '✅', 'Creates parent directories'],
      ['`readdirSync` / `Dirent[]`', '✅', 'Sorted names; `withFileTypes` supported'],
      ['`existsSync` / `statSync`', '✅', '`Stats` shape plus `throwIfNoEntry: false` parity'],
      ['`rmSync({ recursive })`', '✅', 'Tree removal'],
      [
        '`copyFileSync` / `renameSync` / `cpSync`',
        '✅',
        '`COPYFILE_EXCL`, recursive copy, mtime-preserving rename parity',
      ],
      ['Encoding reads', '✅', 'utf8, utf16le, latin1/ascii, hex parity cases'],
      ['Path resolution with `process.cwd()`', '✅', 'Relative fs paths anchor at runtime cwd'],
      ['Callback `readFile` / `writeFile`', '✅', 'Node-style error-first callbacks'],
      [
        '`fs.promises` file ops',
        '✅',
        '`readFile`, `writeFile`, `appendFile`, `readdir`, `copyFile`, `rename`, `rm`, `access`',
      ],
      [
        'fd table',
        '✅',
        '`open`/`close`/`read`/`write`/`fstat`/`ftruncate`; sequential and positional IO',
      ],
      ['`truncate` / zero fill', '✅', 'Sync and promises paths'],
      ['`mkdtemp` / `opendir`', '✅', 'Sync and promises; async directory iteration'],
      ['`createReadStream` / `createWriteStream`', '✅', 'Pipe and `end` smoke tests'],
      [
        '`fs.watch`',
        '⚠️',
        'Conformance covered as cooperative VFS watch subset, not OS-native watcher semantics',
      ],
      [
        'Durable `fsync` / inode-like open-unlink semantics',
        '❌',
        'Tracked as VFS fd durability residual',
      ],
      [
        'Full `FileHandle` object API',
        '❌',
        'Tracked separately; high-frequency fd wall covered first',
      ],
    ],
    tests: [
      '`tests/conformance/builtins/fs.test.ts`',
      '`tests/conformance/builtins/fs-realpath-readdir.test.ts`',
      '`tests/conformance/builtins/fs-streams.test.ts`',
      '`tests/conformance/builtins/fs-watch.test.ts`',
      '`tools/node-parity-runner/cases/fs/*.case.ts`',
    ],
    limitations: [
      '`O_SYNC`, `O_DSYNC`, reflink constants and unsupported numeric flag bits are intentionally absent or rejected.',
      'VFS-level durability beyond OPFS write-through remains a separate lower-layer design.',
    ],
  },
  {
    file: 'streams.md',
    title: 'Compatibility matrix — `node:stream`',
    intro:
      'Public claim surface for the `node:stream` subset used by package servers, fs streams, HTTP bodies, and pipeline-style consumers.',
    rows: [
      ['`Readable` push/data/end', '✅', 'Object mode and byte/string chunks'],
      ['Readable async iteration', '✅', '`for await` over readable chunks'],
      ['`Readable.from(iterable)`', '✅', 'Iterable source support plus options parity cases'],
      ['`Writable` write/end/finish', '✅', 'Backpressure surface via `highWaterMark`'],
      ['`Transform`', '✅', '`_transform` callback path'],
      ['`PassThrough`', '✅', 'Forwards chunks unchanged'],
      ['`pipeline`', '✅', 'Promise/callback chaining, multi-stage, destroy-on-error parity'],
      ['`finished`', '✅', 'Resolves on readable end and cleanup cases'],
      ['`destroy` / cleanup', '✅', 'Writable destroy and async-iterator cleanup parity'],
      ['`stream/consumers`', '✅', 'Text/buffer/json-style consumers covered'],
      ['Legacy pipe/unpipe', '✅', 'Pipe/unpipe and backpressure parity cases'],
      [
        '`Readable.fromWeb`',
        '✅',
        'WHATWG ReadableStream → Node Readable; chunk boundaries + pipe sink tested',
      ],
      ['`node:stream/web` export', '❌', 'WHATWG stream interop tracked separately'],
      ['`Readable.toWeb` / `Writable.toWeb`', '❌', 'Full WHATWG bridge surface is not claimed'],
    ],
    tests: [
      '`tests/conformance/builtins/stream.test.ts`',
      '`tests/conformance/builtins/stream-legacy.test.ts`',
      '`tests/conformance/builtins/stream-consumers.test.ts`',
      '`packages/io/src/streams/readable.from.test.ts`',
      '`packages/net/src/http/response.test.ts`',
      '`tools/node-parity-runner/cases/stream/*.case.ts`',
    ],
    limitations: [
      'The Node stream subset is package-compat focused; complete WHATWG bridge APIs are not yet claimed.',
      'Backpressure is covered at the JS API surface, not as an OS/socket throughput guarantee.',
    ],
  },
  {
    file: 'http.md',
    title: 'Compatibility matrix — `node:http` / `node:https`',
    intro:
      'Public claim surface for rifty HTTP in-browser servers and client loopback via the port registry.',
    rows: [
      ['`http.createServer`', '✅', 'Request handler, `listen(port)`, registered port dispatch'],
      [
        "`server.on('upgrade')` WebSocket",
        '✅',
        'Bridge-backed RFC 6455 upgrade socket; real npm `ws` server and client modes tested on registered local ports',
      ],
      ['Basic GET response', '✅', '`writeHead`, headers, status, body'],
      [
        'POST request body',
        '✅',
        'Readable streaming request body, chunk boundaries, `drain`, and `end`',
      ],
      ['204 / 304 null-body statuses', '✅', 'No invalid fetch `Response` body'],
      [
        'Length-less bodied request framing',
        '✅',
        'Adds Node-shaped body framing for body parsers',
      ],
      ['`server.close()`', '✅', 'Unregisters port and callback fires'],
      [
        '`listen` on a bound port',
        '✅',
        'Emits an async `error` `EADDRINUSE` (errno -98, syscall `listen`) — server not bound, no `listening`; realm-local registry, so this catches an intra-realm double-listen (ADR-0157)',
      ],
      ['Missing port dispatch', '✅', 'Returns 502 through registry dispatch'],
      ['`http.get` loopback', '✅', 'Client request to own registered port'],
      [
        'External WebSocket client egress',
        '✅',
        'Non-local `ws` client upgrades use the native worker/browser `WebSocket` primitive',
      ],
      ['Streaming responses', '✅', 'SSE chunks, long-poll delay, one chunk per `write()`'],
      [
        'Unbounded preview bodies',
        '⚠️',
        'Delivered only where true stream transfer exists; buffered cross-realm paths fail loud (HTTP 502 naming the ceiling) instead of hanging on unending SSE/NDJSON bodies',
      ],
      ['Header reassignment / status codes', '✅', 'Pinned by parity cases'],
      [
        '`https` module surface',
        '❌',
        'Import resolves, but `createServer`, `request`, `get`, and `Agent` throw `NotImplementedError`',
      ],
      ['Real OS sockets', '❌', 'Browser runtime uses port registry, not kernel TCP sockets'],
      ['HTTP/2 implementation', '❌', '`node:http2` is only a loud surface stub today'],
    ],
    tests: [
      '`tests/conformance/builtins/http.test.ts`',
      '`tests/conformance/builtins/http-incoming-body.test.ts`',
      '`tests/conformance/builtins/https.test.ts`',
      '`tools/node-parity-runner/cases/http/*.case.ts`',
      '`tools/node-parity-runner/cases/http2/surface.case.ts`',
      '`packages/net/src/http/client.test.ts`',
      '`packages/service-worker/src/body-transport.test.ts`',
      '`packages/net/src/cross-realm/preview-port.test.ts`',
    ],
    limitations: [
      'Networking is browser-local: servers bind a rifty port registry and preview dispatch, not native sockets.',
      'Raw TCP connect APIs throw directed `NotImplementedError`s; external WebSocket egress is supported through the browser WebSocket primitive, not TCP.',
      'Preview delivery needs true `ReadableStream` transfer for unbounded bodies. Buffered cross-realm paths fail loud (HTTP 502 naming the ceiling) rather than silently buffering forever.',
      '`node:https` cannot promise real TLS egress inside the local runtime without host integration.',
    ],
  },
];

async function listFilesRecursive(dir) {
  const out = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const child = new URL(`${entry.name}${entry.isDirectory() ? '/' : ''}`, dir);
    if (entry.isDirectory()) out.push(...(await listFilesRecursive(child)));
    else if (entry.isFile() && entry.name.endsWith('.test.ts')) out.push(child);
  }
  return out;
}

function table(rows) {
  return [
    '| Feature | Status | Notes |',
    '|---|---|---|',
    ...rows.map(([feature, status, notes]) => `| ${feature} | ${status} | ${notes} |`),
  ].join('\n');
}

function bulletList(items) {
  return items.map((item) => `- ${item}`).join('\n');
}

function renderMatrix(matrix) {
  return `# ${matrix.title}

${generatedNote}

${matrix.intro}

${legend}

${table(matrix.rows)}

## Test Sources

${bulletList(matrix.tests)}

## Known Limitations

${bulletList(matrix.limitations)}
`;
}

function sourcePathFromRendered(rendered) {
  const match = /^`(.+)`$/.exec(rendered);
  if (!match) throw new Error(`compat source must be a backticked path: ${rendered}`);
  return match[1] ?? '';
}

async function sourceMatches(rendered) {
  const source = sourcePathFromRendered(rendered);
  if (!source.includes('*')) {
    const url = new URL(source, rootDir);
    try {
      if ((await stat(url)).isFile()) return [source];
    } catch {
      throw new Error(`compat source does not exist: ${source}`);
    }
    throw new Error(`compat source is not a file: ${source}`);
  }
  if (!source.endsWith('*.case.ts')) {
    throw new Error(`unsupported compat source glob: ${source}`);
  }
  const dir = new URL(source.slice(0, source.lastIndexOf('/') + 1), rootDir);
  const entries = await readdir(dir, { withFileTypes: true });
  const matches = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.case.ts'))
    .map((entry) => `${source.slice(0, source.lastIndexOf('/') + 1)}${entry.name}`);
  if (matches.length === 0) throw new Error(`compat source glob matched no files: ${source}`);
  return matches;
}

async function validateMatrixSources() {
  const seen = new Set();
  for (const matrix of matrices) {
    for (const source of matrix.tests) {
      for (const match of await sourceMatches(source)) seen.add(match);
    }
  }
  return seen.size;
}

function renderReadme() {
  return `# Compatibility matrices

These files are the public claim surface for rifty compatibility. Treat missing areas as
undocumented, not supported. The point is honest fit: tested support, visible caveats, and loud
unsupported rows.

Each markdown here cites the covering tests in \`tests/conformance/\` and \`tests/integration/\` for a
Node-compatible area. \`fs.md\`/\`streams.md\`/\`http.md\` are rendered by \`pnpm compat:generate\` from
static inventories whose cited test files are existence-checked, not re-run — deriving statuses
from test RESULTS is tracked in \`docs/backlog/toolchain-build/compat-matrix-test-result-sink\`.

- [modules.md](./modules.md) — M2 (Modules)
- [buffer.md](./buffer.md) — \`Buffer\` polyfill (\`@riftydev/io\`)
- [fs.md](./fs.md) — \`node:fs\` runtime VFS subset
- [streams.md](./streams.md) — \`node:stream\` subset
- [http.md](./http.md) — \`node:http\` / browser-local port registry subset
- [process.md](./process.md) — process lifecycle / event-loop drain + the drain-cap divergence (ADR-0152); the terminal \`node <file>\` command + its gaps (ADR-0154/0157)
- [wasi.md](./wasi.md) — WASI preview1 syscall surface (\`@riftydev/runtime-wasi\`)
- [incompatible-packages.md](./incompatible-packages.md) — packages rifty can't run (native deps)
- (sqlite.md — coming with the \`node:sqlite\` \`DatabaseSync\` shim, ADR-0065)
- (browsers.md — coming with first cross-browser CI run)

${legend}
`;
}

await mkdir(matrixDir, { recursive: true });
const sourceCount = await validateMatrixSources();
await writeFile(new URL('README.md', matrixDir), renderReadme());
for (const matrix of matrices) {
  await writeFile(new URL(matrix.file, matrixDir), renderMatrix(matrix));
}

const tests = await listFilesRecursive(conformanceDir);
console.log(
  `compat-matrix-generator: wrote ${matrices.length} matrix doc(s); verified ${sourceCount} cited source file(s); scanned ${tests.length} conformance test file(s)`,
);
for (const matrix of matrices) console.log(`  doc: ${matrix.file}`);
