#!/usr/bin/env node
/**
 * Deterministic public compat matrix generator.
 *
 * This intentionally uses static inventories tied to checked-in conformance
 * and parity files. TODO below tracks a separate Vitest JSON reporter sink;
 * milestone claim pages stay deterministic and checked in.
 * TODO(backlog: toolchain-build/compat-matrix-test-result-sink)
 */
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises';

const here = new URL('.', import.meta.url);
const conformanceDir = new URL('../../tests/conformance/', here);
const matrixDir = new URL('../../docs/public/compat/', here);
const rootDir = new URL('../../', here);

const legend =
  'Legend: ✅ implemented and tested · ⚠️ partial / known caveat · ❌ not implemented (throws `NotImplementedError` or `UNSUPPORTED_PROTOCOL`).';

const generatedNote =
  'Generated by `pnpm compat:generate` from static inventories backed by conformance and parity tests.';

const matrices = [
  {
    file: 'fs.md',
    title: 'Compatibility matrix — `node:fs`',
    intro:
      'Public claim surface for the runtime-local `node:fs` subset over rifty VFS. Rows cite existing conformance and node-parity coverage.',
    rows: [
      [
        '`readFileSync` / `writeFileSync`',
        '✅',
        'utf8 strings and binary `Uint8Array`/Buffer-like reads',
      ],
      ['`mkdirSync({ recursive })`', '✅', 'Creates parent directories'],
      [
        '`readdirSync` / `Dirent[]`',
        '✅',
        'Sorted names; `withFileTypes`; `{ recursive: true }` BFS walk + `Dirent.parentPath` (no removed-in-v24 `path` alias)',
      ],
      ['`existsSync` / `statSync`', '✅', '`Stats` shape plus `throwIfNoEntry: false` parity'],
      ['`rmSync({ recursive })`', '✅', 'Tree removal'],
      [
        '`copyFileSync` / `renameSync` / `cpSync`',
        '✅',
        '`COPYFILE_EXCL`, recursive copy, mtime-preserving rename; `cp` `{ filter, force, errorOnExist, preserveTimestamps }`; `dereference` loud-throws (no-symlink, ADR-0050)',
      ],
      [
        '`openAsBlob(path[, { type }])`',
        '✅',
        'Reads VFS bytes into a resolved Blob (default type `""`)',
      ],
      [
        '`lutimesSync` / `futimesSync` / `futimes`',
        '✅',
        'lutimes ≡ utimes (no-symlink); futimes resolves fd→path, `EBADF` (syscall `futime`) on a bad fd',
      ],
      ['Encoding reads', '✅', 'utf8, utf16le, latin1/ascii, hex parity cases'],
      ['Path resolution with `process.cwd()`', '✅', 'Relative fs paths anchor at runtime cwd'],
      ['Callback `readFile` / `writeFile`', '✅', 'Node-style error-first callbacks'],
      [
        '`fs.promises` file ops',
        '✅',
        '`readFile`, `writeFile`, `appendFile`, `readdir`, `copyFile`, `rename`, `rm`, `access`',
      ],
      [
        'fd table',
        '✅',
        '`open`/`close`/`read`/`write`/`fstat`/`ftruncate`; sequential and positional IO',
      ],
      ['`truncate` / zero fill', '✅', 'Sync and promises paths'],
      ['`mkdtemp` / `opendir`', '✅', 'Sync and promises; async directory iteration'],
      [
        '`createReadStream` / `createWriteStream`',
        '✅',
        'Async `Vfs.openReadable` first, chunked reads, pipe and `end` smoke tests',
      ],
      [
        '`fs.watch`',
        '⚠️',
        'Conformance covered as cooperative VFS watch subset, not OS-native watcher semantics',
      ],
      [
        'Durable `fsync` / inode-like open-unlink semantics',
        '❌',
        'Tracked as VFS fd durability residual',
      ],
      [
        'Full `FileHandle` object API',
        '❌',
        'Tracked separately; high-frequency fd wall covered first',
      ],
    ],
    tests: [
      '`tests/conformance/builtins/fs.test.ts`',
      '`tests/conformance/builtins/fs-realpath-readdir.test.ts`',
      '`tests/conformance/builtins/fs-streams.test.ts`',
      '`tests/conformance/builtins/shared-vfs.test.ts`',
      '`tests/conformance/builtins/fs-watch.test.ts`',
      '`tools/node-parity-runner/cases/fs/*.case.ts`',
    ],
    limitations: [
      '`O_SYNC`, `O_DSYNC`, reflink constants and unsupported numeric flag bits are intentionally absent or rejected.',
      'VFS-level durability beyond OPFS write-through remains a separate lower-layer design.',
    ],
  },
  {
    file: 'streams.md',
    title: 'Compatibility matrix — `node:stream`',
    intro:
      'Public claim surface for the `node:stream` subset used by package servers, fs streams, HTTP bodies, and pipeline-style consumers.',
    rows: [
      ['`Readable` push/data/end', '✅', 'Object mode and byte/string chunks'],
      ['Readable async iteration', '✅', '`for await` over readable chunks'],
      ['`Readable.from(iterable)`', '✅', 'Iterable source support plus options parity cases'],
      ['`Writable` write/end/finish', '✅', 'Backpressure surface via `highWaterMark`'],
      ['`Transform`', '✅', '`_transform` callback path'],
      ['`PassThrough`', '✅', 'Forwards chunks unchanged'],
      ['`pipeline`', '✅', 'Promise/callback chaining, multi-stage, destroy-on-error parity'],
      ['`finished`', '✅', 'Resolves on readable end and cleanup cases'],
      ['`destroy` / cleanup', '✅', 'Writable destroy and async-iterator cleanup parity'],
      ['`stream/consumers`', '✅', 'Text/buffer/json-style consumers covered'],
      ['Legacy pipe/unpipe', '✅', 'Pipe/unpipe and backpressure parity cases'],
      [
        '`Readable.fromWeb`',
        '✅',
        'WHATWG ReadableStream → Node Readable; chunk boundaries + pipe sink tested',
      ],
      ['`node:stream/web` export', '❌', 'WHATWG stream interop tracked separately'],
      ['`Readable.toWeb` / `Writable.toWeb`', '❌', 'Full WHATWG bridge surface is not claimed'],
    ],
    tests: [
      '`tests/conformance/builtins/stream.test.ts`',
      '`tests/conformance/builtins/stream-legacy.test.ts`',
      '`tests/conformance/builtins/stream-consumers.test.ts`',
      '`packages/io/src/streams/readable.from.test.ts`',
      '`packages/net/src/http/response.test.ts`',
      '`tools/node-parity-runner/cases/stream/*.case.ts`',
    ],
    limitations: [
      'The Node stream subset is package-compat focused; complete WHATWG bridge APIs are not yet claimed.',
      'Backpressure is covered at the JS API surface, not as an OS/socket throughput guarantee.',
    ],
  },
  {
    file: 'http.md',
    title: 'Compatibility matrix — `node:http` / `node:https`',
    intro:
      'Public claim surface for rifty HTTP in-browser servers and client loopback via the port registry.',
    rows: [
      ['`http.createServer`', '✅', 'Request handler, `listen(port)`, registered port dispatch'],
      [
        "`server.on('upgrade')` WebSocket",
        '✅',
        'Bridge-backed RFC 6455 upgrade socket; real npm `ws` server and client modes tested on registered local ports',
      ],
      ['Basic GET response', '✅', '`writeHead`, headers, status, body'],
      [
        'POST request body',
        '✅',
        'Readable streaming request body, chunk boundaries, `drain`, and `end`',
      ],
      ['204 / 304 null-body statuses', '✅', 'No invalid fetch `Response` body'],
      [
        'Length-less bodied request framing',
        '✅',
        'Adds Node-shaped body framing for body parsers',
      ],
      ['`server.close()`', '✅', 'Unregisters port and callback fires'],
      [
        '`listen` on a bound port',
        '✅',
        'Emits an async `error` `EADDRINUSE` (errno -98, syscall `listen`) — server not bound, no `listening`; realm-local registry, so this catches an intra-realm double-listen (ADR-0157)',
      ],
      [
        '`listen(0)` / `listen({ port: 0 })` ephemeral',
        '✅',
        'Allocates a free virtual port from the realm registry; `address().port` reflects it until `close()`; distinct per concurrent server (parity-pinned)',
      ],
      ['Missing port dispatch', '✅', 'Returns 502 through registry dispatch'],
      ['`http.get` loopback', '✅', 'Client request to own registered port'],
      [
        'External WebSocket client egress',
        '✅',
        'Non-local `ws` client upgrades use the native worker/browser `WebSocket` primitive',
      ],
      ['Streaming responses', '✅', 'SSE chunks, long-poll delay, one chunk per `write()`'],
      [
        'Unbounded preview bodies',
        '⚠️',
        'Delivered only where true stream transfer exists; buffered cross-realm paths fail loud (HTTP 502 naming the ceiling) instead of hanging on unending SSE/NDJSON bodies',
      ],
      ['Header reassignment / status codes', '✅', 'Pinned by parity cases'],
      [
        'Response header introspection',
        '✅',
        '`getHeaders` (null-proto, value types preserved), `getHeaderNames`, `hasHeader`, `appendHeader` (array-merge); post-send `ERR_HTTP_HEADERS_SENT` (parity-pinned)',
      ],
      ['`http.METHODS`', '✅', 'Static verb list beside `STATUS_CODES` for per-verb routers'],
      [
        '`http.maxHeaderSize`',
        '⚠️',
        'Exposes the 16384 default but ADVISORY ONLY — header framing is the SW/fetch bridge’s, never enforced from this value',
      ],
      [
        '`writeContinue` / `writeEarlyHints` / `addTrailers`',
        '❌',
        'Interim 100/103 + trailers are unmodelable over the single-status fetch/SW Response bridge — throw `NotImplementedError` (never fake-ack)',
      ],
      [
        '`https` module surface',
        '❌',
        'Import resolves, but `createServer`, `request`, `get`, and `Agent` throw `NotImplementedError`',
      ],
      ['Real OS sockets', '❌', 'Browser runtime uses port registry, not kernel TCP sockets'],
      ['HTTP/2 implementation', '❌', '`node:http2` is only a loud surface stub today'],
    ],
    tests: [
      '`tests/conformance/builtins/http.test.ts`',
      '`tests/conformance/builtins/http-incoming-body.test.ts`',
      '`tests/conformance/builtins/https.test.ts`',
      '`tools/node-parity-runner/cases/http/*.case.ts`',
      '`tools/node-parity-runner/cases/http2/surface.case.ts`',
      '`packages/net/src/http/client.test.ts`',
      '`packages/service-worker/src/body-transport.test.ts`',
      '`packages/net/src/cross-realm/preview-port.test.ts`',
    ],
    limitations: [
      'Networking is browser-local: servers bind a rifty port registry and preview dispatch, not native sockets.',
      'Raw TCP connect APIs throw directed `NotImplementedError`s; external WebSocket egress is supported through the browser WebSocket primitive, not TCP.',
      'Preview delivery needs true `ReadableStream` transfer for unbounded bodies. Buffered cross-realm paths fail loud (HTTP 502 naming the ceiling) rather than silently buffering forever.',
      '`node:https` cannot promise real TLS egress inside the local runtime without host integration.',
    ],
  },
  {
    file: 'zlib.md',
    title: 'Compatibility matrix — `node:zlib`',
    intro:
      'Public claim surface for the `node:zlib` web-compression-backed async subset (ADR-0159): one-shot gzip/deflate over the host `CompressionStream`/`DecompressionStream`, wire-compatible with real Node both directions (conformance-pinned).',
    rows: [
      [
        '`gzip` / `gunzip` (async)',
        '✅',
        "`CompressionStream('gzip')` — RFC-1952; rifty output reads in Node and vice versa",
      ],
      [
        '`deflate` / `inflate` (async)',
        '✅',
        "`'deflate'` — RFC-1950 zlib-wrapped; both-direction wire-compat",
      ],
      [
        '`deflateRaw` / `inflateRaw` (async)',
        '✅',
        "`'deflate-raw'` — RFC-1951 raw; both-direction wire-compat",
      ],
      ['`util.promisify(zlib.gzip)`', '✅', 'Standard `(err, Buffer)` callback convention'],
      [
        'String / Buffer / TypedArray / ArrayBuffer input',
        '✅',
        'Normalised to bytes, utf-8 for strings',
      ],
      [
        '`constants` / `codes`',
        '✅',
        'Full real Node table; legacy top-level aliases are non-enumerable; `codes` frozen (Node shape)',
      ],
      [
        '`maxOutputLength` option',
        '✅',
        'Honored — output reader aborts early and throws `RangeError [ERR_BUFFER_TOO_LARGE]` (decompression-bomb guard, matches Node)',
      ],
      [
        'Compression `level` / `strategy` options',
        '⚠️',
        'Accepted but not applied (Web API has no level control); output stays valid and round-trips, bytes differ from Node',
      ],
      [
        'Decompression error `code` / `errno`',
        '⚠️',
        "Corrupt input rejects with an `Error` (error-first holds), but codes are the browser stream's, not Node's `Z_DATA_ERROR`",
      ],
      [
        '`gzipSync` / `gunzipSync` / `*Sync`',
        '❌',
        'Web compression is async-only; no honest sync path',
      ],
      ['Brotli (`brotliCompress` / …)', '❌', 'No Web API for brotli in the realm'],
      ['Zstd (`zstdCompress` / …)', '❌', 'No Web API for zstd in the realm'],
      ['`crc32`', '❌', 'Deferred — not part of the compression subset'],
      [
        '`createGzip` / `Gzip`',
        '⚠️',
        "`CompressionStream('gzip')` bridged to a Node-shaped `Transform`; gzip bytes are readable by real Node. Flush-opcode options (`flush` / `finishFlush`) throw rather than pretending parity",
      ],
      [
        'Other Transform streams (`createGunzip` / `createDeflate` / …)',
        '❌',
        'Remaining stream factories/classes stay loud until their own parity surface lands',
      ],
      ['`unzip` (gzip/zlib auto-detect)', '❌', 'Header-sniff deferred to its own parity surface'],
      [
        '`flush` / `finishFlush` / `windowBits` / `dictionary` / truthy `info` options',
        '❌',
        'Throw `NotImplementedError`. `CompressionStream` exposes no flush opcodes, emits a fixed max window, and has no dictionary/engine handle; ignoring these would fake wire bytes, chunking, or return shape. `info:false` is a no-op',
      ],
    ],
    tests: [
      '`tests/conformance/builtins/zlib.test.ts`',
      '`tools/node-parity-runner/cases/zlib/*.case.ts`',
    ],
    limitations: [
      'Web compression is async-only and exposes no level/window/dictionary/flush control: sync variants throw, size-only knobs (`level`/`strategy`/…) are inert no-ops, `flush`/`finishFlush`/`windowBits`/`dictionary`/truthy-`info` throw rather than silently lie (ADR-0159/0178).',
      'Brotli and zstd have no browser primitive — loud `NotImplementedError`.',
      'Only the gzip Transform subset is implemented (`createGzip` / `Gzip`); flush-opcode options and the rest of the Transform-stream surface are still loud ceilings.',
    ],
  },
  {
    file: 'ts-language-service.md',
    title: 'Compatibility matrix — TS language service (`@riftydev/ts-language-service`)',
    intro:
      "Public claim surface for the in-browser `ts.LanguageService` over the rifty VFS (ADR-0166/0177): a real project-installed `typescript` LanguageService in a kernel worker, LSP-shaped, wired as real Monaco providers where standalone Monaco exposes that provider shape (Monaco's built-in TS intelligence retired for project-aware rows). Every ✅/⚠️ row is parity-checked head-to-head against the real `ts.LanguageService` where the row claims TS parity (gold standard, same compiler version on both sides; workspace-TS loader has its own regression), and ⚠️ rows name their caveat/backlog explicitly. ❌ rows are browser/editor ceilings or out-of-scope surfaces — no silent stub.",
    rows: [
      [
        'Diagnostics (semantic / syntactic / tsconfig-config)',
        '⚠️',
        '`getSemanticDiagnostics` / `getSyntacticDiagnostics` / config-file diagnostics over the project tsconfig + VFS; `relatedInformation` and `DiagnosticTag.Unnecessary` / `DiagnosticTag.Deprecated` are parked in `backlog/toolchain-build/ts-language-service-diagnostic-tags`',
      ],
      [
        'Hover / quick-info',
        '✅',
        '`getQuickInfo` — cross-file + `node_modules` symbol types; honors clone-safe `maximumLength`',
      ],
      [
        'Go-to-definition / type-definition',
        '✅',
        '`getDefinitionAtPosition` / `getTypeDefinitionAtPosition` — cross-file + into `node_modules` `.d.ts`',
      ],
      [
        'Completions (+ resolve)',
        '✅',
        '`getCompletionsAtPosition` + lazy `getCompletionEntryDetails`; preserves TS list flags/global/member/new-identifier/`metadata`, replacement spans, snippets, commit characters, `source`/`data`, completion code-action edits/commands, and clone-safe TS preferences/format settings including deprecated `includeExternalModuleExports`; Monaco applies text-only completion edits and refuses command-bearing workspace edits rather than partially applying side effects',
      ],
      ['Find-references', '✅', '`findReferences` flattened; honors `includeDeclaration`'],
      [
        'Flat references + lifecycle cache/dispose',
        '✅',
        '`getReferencesAtPosition` / `toLineColumnOffset` / `cleanupSemanticCache` / `dispose` exposed by engine/protocol/client',
      ],
      [
        'Rename (+ prepare-rename)',
        '✅',
        '`getRenameInfo` + `findRenameLocations` / import-path `getEditsForFileRename` → cross-file `WorkspaceEdit`; non-renameable element rejected; honors clone-safe rename preferences and string/comment search flags. Import-path file rename is exposed through service/protocol/client; Monaco rename remains symbol/string-edit UI only.',
      ],
      ['Signature help', '✅', '`getSignatureHelpItems` — real overloads at a call site'],
      [
        'Quick-fixes / code-actions',
        '✅',
        '`getCodeFixesAtPosition` → `CodeAction[]` (kind `quickfix`); request span within the diagnostic span',
      ],
      [
        'Organize imports',
        '✅',
        "`organizeImports({type:'file'})` — sort + de-dup + drop unused; honors TS `mode` / `skipDestructiveCodeActions`",
      ],
      [
        'Document + range formatting',
        '✅',
        "`getFormattingEditsForDocument` / `getFormattingEditsForRange` — tsserver's real `FormatCodeSettings`",
      ],
      [
        'Refactorings',
        '⚠️',
        '`getApplicableRefactors` / `getEditsForRefactor` / `getMoveToRefactoringFileSuggestions`; preserves parent/action metadata, edit commands, not-applicable reasons, and post-edit rename metadata; honors clone-safe preferences/filter knobs; text-only non-interactive actions carry edits into Monaco, while post-edit-rename/interactive actions are protocol/client metadata until `backlog/playground/ts-refactor-interactive-ui` lands',
      ],
      [
        'Inlay hints',
        '⚠️',
        '`provideInlayHints` wired to Monaco inlay-hints provider; clone-safe TS inlay preferences are passed faithfully, including `undefined`; visible labels/kind/padding are parity-covered, but interactive `displayParts` label metadata is parked in `backlog/toolchain-build/ts-language-service-inlay-label-parts`',
      ],
      [
        'Document highlights',
        '✅',
        '`getDocumentHighlights` wired to Monaco document-highlight provider',
      ],
      [
        'Semantic highlighting (classification)',
        '⚠️',
        '`getSemanticClassifications` / `getSyntacticClassifications` raw classified spans plus encoded classifications; document + range semantic tokens providers use TS 2020 encoded classifications, while encoded default/original-format parity is parked in `backlog/toolchain-build/ts-language-service-encoded-classification-format`',
      ],
      [
        'Call hierarchy',
        '✅',
        '`prepareCallHierarchy` / `provideCallHierarchy{Incoming,Outgoing}Calls` exposed by engine/protocol/client; standalone Monaco 0.52 has no public call-hierarchy provider',
      ],
      [
        'Document symbols / outline + folding + workspace symbols',
        '✅',
        '`getNavigationTree` / `getOutliningSpans` wired to Monaco; full `getNavigateToItems(search,maxResultCount,fileName,excludeDtsFiles,excludeLibFiles)` exposed by engine/protocol/client (no standalone workspace-symbol provider in Monaco 0.52)',
      ],
      [
        'On-type formatting',
        '✅',
        '`getFormattingEditsAfterKeystroke` wired for `;`, `}`, and Enter',
      ],
      [
        'Code lens',
        '❌',
        'Editor-only convenience, not a `ts.LanguageService` primitive — outside the TS hard-ceil surface',
      ],
      [
        'Non-TS/JS LSP (Python / Go native servers)',
        '❌',
        'A browser ceiling (no native language servers) — out of scope (ADR-0166)',
      ],
      [
        "Project's installed TS version (workspace version)",
        '✅',
        'Requires `node_modules/typescript/lib/typescript.js` + adjacent `lib/*.d.ts` from the project; missing or broken workspace TypeScript fails loudly (ADR-0177)',
      ],
      [
        'Name/dotted span · breakpoint · navigation bar',
        '✅',
        '`getNameOrDottedNameSpan` / `getBreakpointStatementAtPosition` / `getNavigationBarItems` exposed by engine/protocol/client',
      ],
      [
        'Go-to-implementation · suggestion diagnostics · definition-bound-span',
        '✅',
        '`getImplementationAtPosition` / `getSuggestionDiagnostics` / `getDefinitionAndBoundSpan`',
      ],
      [
        'Fix-all · update-imports-on-rename · selection range · file references',
        '✅',
        '`getCombinedCodeFix` / `getEditsForFileRename` / `getSmartSelectionRange` / `getFileReferences`',
      ],
      [
        'JSX close-tag completion + linked editing',
        '✅',
        '`getJsxClosingTagAtPosition` / `getLinkedEditingRangeAtPosition`; linked editing wired to Monaco',
      ],
      [
        'Paste-with-imports · JSDoc template · TODO comments · compiler-options diagnostics',
        '✅',
        '`preparePasteEditsForFile` / `getPasteEdits` / `getDocCommentTemplateAtPosition` / `getTodoComments` / `getCompilerOptionsDiagnostics`; paste preserves TS `fixId` and is exposed over protocol/client (no Monaco paste provider in 0.52)',
      ],
      [
        'Brace matching · comment toggling · indentation',
        '✅',
        '`getBraceMatchingAtPosition` / `getIndentationAtPosition` / `isValidBraceCompletionAtPosition` / `getSpanOfEnclosingComment` / comment toggles exposed by engine/protocol/client; Monaco keeps its native editor UI for these commands',
      ],
      [
        'Emit output · supported code-fix inventory',
        '✅',
        '`getEmitOutput` / `getSupportedCodeFixes` exposed by engine/protocol/client',
      ],
      [
        'Apply code-action command',
        '❌',
        '`applyCodeActionCommand` currently carries package-install side effects (`InstallPackageAction`), not VFS text edits; rifty exposes a loud `NotImplementedError` instead of fake-applying it',
      ],
      [
        'Program / Symbol object graph APIs',
        '❌',
        '`getProgram`, `getCompletionEntrySymbol`, and `getCompletions({includeSymbol:true})` / `getCompletions({preferences:{includeSymbol:true}})` return live TypeScript compiler object graphs/Symbols that are not structured-clone-safe across the worker protocol; rifty exposes loud feature-tagged `NotImplementedError`s instead of fake stand-ins',
      ],
    ],
    tests: [
      '`packages/ts-language-service/src/parity.test.ts`',
      '`packages/ts-language-service/src/long-tail-parity.test.ts`',
      '`packages/ts-language-service/src/service.test.ts`',
      '`packages/ts-language-service/src/config-diagnostics.test.ts`',
      '`packages/ts-language-service/src/hard-ceil-source.test.ts`',
      '`tests/e2e/ts-language-service.spec.ts`',
    ],
    limitations: [
      'Editor capability, not a Node API module: rows are `ts.LanguageService` queries (LSP-shaped), backed by the playground Monaco providers — not `node:*` surface.',
      'TS/JS only. Other languages (Python/Go) need native language servers — a browser ceiling, out of scope (ADR-0166).',
      'Standalone Monaco 0.52 does not expose public provider registration for call hierarchy, workspace symbols, or paste edits. Those TS APIs are still exposed through the rifty engine/protocol/client.',
      'Interactive inlay label parts, encoded semantic default/original format, and playground UI for interactive/post-edit-rename refactors are parked backlog items and therefore ⚠️, not fake ✅ claims.',
      'The Monaco editor path applies workspace edits atomically; if any target model cannot be opened, the provider rejects instead of partially applying edits.',
      'Code lens and non-TS/JS LSP remain out of scope/browser ceilings.',
      'TypeScript `applyCodeActionCommand` is classified as an external package-install side-effect channel; text edits from code fixes/refactors/completions are implemented separately.',
      'TypeScript object-graph APIs (`getProgram`, `getCompletionEntrySymbol`, completion `includeSymbol`) remain explicit ❌ because their return values are live compiler internals, not cloneable protocol values.',
      'Missing or broken workspace TypeScript fails loudly instead of falling back to rifty vendored TypeScript.',
    ],
  },
  {
    file: 'git.md',
    title: 'Compatibility matrix — git (`@riftydev/git`)',
    intro:
      'Public claim surface for git over the VFS (isomorphic-git, ADR-0167). Local objects are canonical git objects (same SHA-1s for identical inputs); selected porcelain text is parity-pinned where stated. The network is smart-HTTP only — every browser-ceiling gap throws `NotImplementedError`, never a silent stub.',
    rows: [
      ['`init` / `remove`', '✅', 'Local index + object writes over the Memory VFS'],
      [
        '`add <pathspec…>` / `add .` / `-A` / `-u` / `-f`',
        '✅',
        "ALL-OR-NOTHING (a single unmatched pathspec stages nothing → `fatal: pathspec … did not match`); a gone-but-tracked path stages its deletion; an explicit `.gitignore`-ignored path is refused (`-f` overrides, including ignored children reached via `.`/directory pathspecs); no pathspec → git's `Nothing specified, nothing added.` (exit 0). Unknown flag → `NotImplementedError('git.add.<flag>')` (exit 128), never silently dropped",
      ],
      [
        '`.gitignore` honored',
        '✅',
        "Ignored paths (`node_modules/`, build output, `*.log`) are excluded from `git status`, `git add .`, and `git diff` — the fs-adapter reads `.gitignore` via the string-encoding `readFile` form iso-git's ignore manager uses",
      ],
      [
        'Repository guard',
        '✅',
        'Every verb but `init`/`clone` verifies a VALID repo governs the cwd first — real git discovery (walking up) requiring `.git/HEAD`, so a bare/empty/partial `.git` is rejected. NON-repo → `fatal: not a git repository (or any of the parent directories): .git` (exit 128) — never a silent false-success',
      ],
      [
        '`commit` / `commit -a` / `commit --amend`',
        '✅',
        "Canonical git objects — **identical 40-hex SHA-1 to real git** for identical inputs (author+committer identity/timestamp/tz explicit); parity-pinned. `-a`/`-am` stage tracked modifications+deletions (`git add -u`); repeated `-m` join as paragraphs; an empty `-m ''` → `Aborting commit due to empty commit message.` (exit 1). REFUSES an empty commit (real git exit 1, `nothing to commit…`), never fabricates one. Unknown `commit` flag → `NotImplementedError('git.commit.<flag>')` (exit 128). `--amend` replaces HEAD (reuses prior message when no `-m`)",
      ],
      [
        'Author identity from config',
        '✅',
        '`GIT_AUTHOR_*` env → `user.name`/`user.email` config → built-in default; `git config user.email x` then `git commit` (no env) authors as x',
      ],
      [
        '`status --porcelain`',
        '✅',
        'Byte-exact vs git 2.50.1 (frozen golden fixtures); path-sorted XY codes',
      ],
      [
        '`log` / `log --oneline` / `-n` / `--format` / `<ref>` / `a..b` / `-- <path>`',
        '⚠️',
        'Byte-exact short-oid + subject for the frozen fixture core; bounded flags support agent workflows (`%H`, `%h`, `%s`, `%an`, `%ae`) plus parent-range exclusion and single-path history filtering. Default long log is structured and includes merge parents, but does not yet render every real-git header such as `Date:`. Non-integer `-n`/`--max-count` is fatal, never a full-log fallback',
      ],
      [
        '`diff` / `--staged` / `--cached [<rev>]` / `diff <rev> [<path>]` / `diff <a> <b> [<path>]`',
        '⚠️',
        'Correct tree selection: bare = index↔workdir tracked files, staged = tree↔index (unborn HEAD = empty tree), one ref = tree↔workdir with index-gated additions, two refs = tree↔tree. Pathspecs work with or without `--`; missing pathspecs yield an empty diff; trailing-slash directory pathspecs match descendants. `--name-only`, `--name-status`, and `--stat` are supported. Binary changes render `Binary files … differ`. Hunk body is structured LCS, NOT byte-exact git diff text',
      ],
      ['`branch` / `listBranches` / `currentBranch` / `resolveRef`', '✅', 'Local refs'],
      [
        '`checkout <branch>` / `-b [<start>]` / `<commit>` (detached)',
        '✅',
        "Branch switch, create+switch, detached HEAD; byte-exact stderr vs git 2.50.1 (frozen fixtures); dirty-tree conflict refused with git's exact `error:…Aborting` message (exit 1)",
      ],
      [
        '`checkout [--] <pathspec>` / `<tree-ish> -- <pathspec>` (restore)',
        '✅',
        'Restore worktree from the index (or from a tree-ish, +index); HEAD untouched; silent like git',
      ],
      [
        'checkout `--orphan` / `-B` / `--patch` / `--merge` / `--ours`·`--theirs` / `--track` / `-` / glob pathspec / reflog revspec (`@{…}`)',
        '❌',
        "`NotImplementedError('git.checkout.<x>')` (exit 128) — out of the v1 checkout subset, never a leaked plumbing error, never mislabeled as a typo",
      ],
      [
        '`switch <branch>` / `-c [<start>]` / `--detach <commit>`',
        '✅',
        "Branch-only switch / create+switch / detach; byte-exact stderr vs git 2.50.1 (frozen fixtures). `switch --detach` prints the HEAD-line ONLY (no advisory). A non-`--detach` commit → git's `fatal: a branch is expected, got commit` (exit 128); a name that is neither a branch nor any ref → `fatal: invalid reference: <name>` (exit 128); `switch -` (previous branch) → `NotImplementedError('git.switch.previous')` (no reflog)",
      ],
      [
        '`restore [--staged] [--source=<tree>] <pathspec>`',
        '✅',
        "Restore worktree from index/tree, or `--staged` unstage (index ← HEAD); `--source=HEAD~1` parent arithmetic works; silent like git. `--staged --source` → `NotImplementedError('git.restore.staged-source')`; no-match → pathspec-miss (exit 1)",
      ],
      [
        '`reset <path>` / `reset --soft|--mixed|--hard <rev>`',
        '✅',
        'Path reset (`reset [HEAD] -- <path>`) unstages without touching the worktree; tree reset moves HEAD with real soft/mixed/hard index/worktree semantics, including hard-reset removal of tracked paths absent from the target tree, mixed-reset `Unstaged changes after reset:` output, and the hard-reset `HEAD is now at …` stdout summary. Annotated commit tags peel before ref writes; non-commit tag targets are rejected before moving HEAD. Mode+pathspec forms (`reset --hard <path>`) loud-throw until non-HEAD path resets are implemented. Parent arithmetic (`HEAD~1`, `main^`, `HEAD^0`) supported; reflog/peel revspecs stay loud ceilings',
      ],
      [
        '`show <rev>` / `show <rev>:<path>`',
        '⚠️',
        'Commit/tree/tag/blob reads over the object database; commit show prints the summary plus structured patch vs first parent (root commit vs empty tree), while merge commits print `Merge:` and omit the patch like real git. Patch text is structured, not byte-exact full git diff headers. Blob path form prints bytes from the selected tree and reports the selected blob oid',
      ],
      [
        '`tag` list / lightweight / annotated / delete',
        '✅',
        'Local tag refs via isomorphic-git (`tag`, `annotatedTag`, `deleteTag`); GPG signing is a loud ceiling',
      ],
      [
        '`remote` list / `-v` / add / remove / `ls-remote <url|remote>`',
        '✅',
        'Local remotes are config-backed; `remote add/remove` reject unsupported flags and extra operands before mutating config. `ls-remote --tags/--heads` maps to server-ref prefixes; `ls-remote origin` and bare `ls-remote` (default `origin`) resolve the remote URL before transport checks; no configured origin reports the real fatal. Smart HTTP shares the same transport/CORS loud ceilings as clone/fetch/push',
      ],
      [
        '`merge` / `cherry-pick` / `stash`',
        '⚠️',
        "Backed by isomorphic-git primitives and covered for clean fast-forward/non-fast-forward merge, clean cherry-pick, and tracked-file stash push/list/pop/apply/drop with `stash@{n}` selection. Stash uses temporary identity without persisting fallback `user.name`/`user.email` into config. Extra merge/cherry-pick operands and unsupported flags loud-throw before mutation. isomorphic-git's stash is tracked-files only: `stash -u`/`--include-untracked`/`--all` → `NotImplementedError('git.stash.include-untracked')`; `stash push <pathspec>` → `git.stash.pathspec`; `stash show -p` is not implemented. Complex conflict workflows (`merge --continue`, custom strategies, conflict marker/index state) remain loud ceilings",
      ],
      [
        '`revert <commit>`',
        '⚠️',
        "Clean single-parent commit revert only: requires a clean worktree and every touched path to still match the reverted commit's post-image, then writes the inverse and records a normal `Revert \"<subject>\"` commit. Dirty worktrees, conflicts, merge commits/mainline, multiple commits, `--no-commit`, and sequencer modes (`--continue|--abort|--quit|--skip`) loud-throw via `NotImplementedError('git.revert.<x>')` before mutation",
      ],
      [
        '`apply <patch-file>` / `apply -`',
        '⚠️',
        'Clean text unified-diff applier over the VFS worktree (not the index): add/modify/delete hunks, file path or stdin, all-or-nothing preflight. From repo subdirectories, patch entries outside cwd scope are ignored before unsupported metadata is interpreted. Context mismatch leaves every file untouched and exits 1 with git-style `patch failed` / `patch does not apply` text. `--3way`, `--index`/`--cached`, `--check`, reverse/reject/stat modes, binary patches, renames/copies, mode-only changes, quoted/unsafe paths, and no-final-newline hunks are directed ceilings',
      ],
      [
        '`rm` / `mv`',
        '⚠️',
        "`rm` refuses modified tracked files unless forced, treats `-r` as recursion (not force), validates all pathspecs before mutation, and prints `rm '<path>'` on success. `mv` refuses untracked sources before mutation, moves files into existing directories, and refuses destination overwrite unless forced; `mv <dir>` is still `NotImplementedError('git.mv.directory')`. Both update VFS and index together for tracked files",
      ],
      [
        '`config <key>` / `config <key> <value>`',
        '⚠️',
        "Bounded get/set on `.git/config`: `<key>` prints the value (unset → exit 1, silent), `<key> <value>` writes it. Value-pattern/multi-value forms and `--list`/`--get-all`/`--unset`/other flags → `NotImplementedError('git.config.<x>')` (exit 128) — no full-dump/multi-value primitive in iso-git",
      ],
      [
        '`clone <url> [<dir>]` / `fetch [<remote>]` / `pull [<remote> <ref>]` / `push [<remote> <ref>]` (smart HTTP)',
        '✅',
        'Over rifty `node:http` egress; real `git http-backend` clone integration-tested (canonical objects end-to-end). `clone` writes a NEW subdirectory (url basename or explicit `<dir>`), not the cwd; no URL exits 129 with usage; a non-empty destination is refused (`fatal: destination path … already exists…`, exit 128). `fetch`/`pull`/`push` accept a remote NAME (`git push origin main`) resolved from config — not mistaken for a URL transport; `clone`/`fetch` parse `--depth` and `--single-branch`; `clone` parses `--no-tags`; `fetch` parses single `src:dst` refspecs plus `--tags`/`--prune`/`--prune-tags`; `push` parses single `src:dst`, delete refspecs, and `--tags`; multi/wildcard refspecs stay loud ceilings',
      ],
      [
        '`corsProxy`',
        '✅',
        'Env-config `RIFTY_GIT_CORS_PROXY` (D-004) — never hardcoded; unset → cross-origin clone throws',
      ],
      ['`onAuth` (HTTPS Basic / PAT)', '✅', 'Injected token provider for private repos + push'],
      [
        'Verb from a subdirectory of the repo',
        '✅',
        'Repo discovery walks up to `.git/HEAD`; cwd-relative pathspecs are translated to root-relative paths for add/diff/log/checkout/restore/reset/rm/mv. Output paths remain repo-root-relative like the existing porcelain surface',
      ],
      [
        'Shallow `depth` / `singleBranch` / tag flags',
        '✅',
        'Passed through to clone/fetch where supported by isomorphic-git',
      ],
      [
        'SSH (`ssh://`, `git@host:`)',
        '❌',
        "`NotImplementedError('git.transport.ssh')` — no raw TCP/SSH in the browser",
      ],
      [
        'Native `git://` / dumb-HTTP',
        '❌',
        "`NotImplementedError('git.transport.git')` — smart-HTTP is the only in-browser transport",
      ],
      [
        'Cross-origin smart-HTTP without a proxy',
        '❌',
        "`NotImplementedError('git.cors')` in the browser (same-origin ceiling) — set `RIFTY_GIT_CORS_PROXY`; GitHub/GitLab/Bitbucket send no CORS headers",
      ],
      [
        'Executable bit (`100755`) & symlinks',
        '❌',
        'VFS has no exec-bit/symlink layer (ADR-0050/0167) → file mode fixed `100644`; tree-SHA diverges from canonical git for such repos — recorded, never silently wrong',
      ],
      [
        'CRLF / `.gitattributes` / clean-smudge filters',
        '❌',
        'No line-ending normalization — a known SHA-divergence source for repos that rely on it',
      ],
      [
        'GPG commit signing',
        '❌',
        'Unsigned only — `user.signingkey`/`commit.gpgsign` not honored',
      ],
      [
        'Push from a shallow clone',
        '❌',
        'Surfaced loud (isomorphic-git `GitPushError`), no silent retry',
      ],
      [
        'rebase / am / submodules / worktrees / sparse + partial clone',
        '❌',
        'Out of the current browser/VFS-backed subset — throw `NotImplementedError`; `am` needs a real mailbox engine, never a fake patch applier',
      ],
      ['gc / repack / prune / reflog / bisect / blame / hooks', '❌', 'Out of the v1 subset'],
    ],
    tests: [
      '`packages/git/tests/commit-sha-parity.test.ts`',
      '`packages/git/tests/fs-adapter.test.ts`',
      '`packages/git/tests/capability-local.test.ts`',
      '`packages/git/tests/checkout.test.ts`',
      '`packages/git/tests/diff.test.ts`',
      '`packages/git/tests/cors-proxy.test.ts`',
      '`packages/git/tests/http-plugin.test.ts`',
      '`packages/git/tests/loud-throws.test.ts`',
      '`packages/git/tests/network.integration.test.ts`',
      '`packages/shell/tests/git-cli.test.ts`',
      '`packages/shell/tests/git-fixtures.test.ts`',
    ],
    limitations: [
      'git runs as pure JS (isomorphic-git) over the Memory VFS — local porcelain writes canonical git objects, so commit/tree/blob SHA-1s match real git exactly; the network is smart-HTTP only.',
      'Browser same-origin ceiling: GitHub/GitLab/Bitbucket smart-HTTP endpoints send no CORS headers, so cross-origin clone/fetch/push need `RIFTY_GIT_CORS_PROXY` (D-004) or a CORS-enabled host; SSH and `git://` need raw TCP that the browser has not. All throw `NotImplementedError` — never a silent network failure.',
      'The VFS has no exec-bit or symlink layer (ADR-0050/0167): file mode is fixed `100644`, so repos containing executable files or symlinks diverge in tree-SHA from canonical git. Recorded as a loud limitation, not a silent lie.',
      'Exotic plumbing (rebase, conflict-aware revert/apply, apply 3-way/index/mailbox modes, am patch-mailbox workflows, submodules, worktrees, sparse/partial clone, gc, reflog, bisect, blame, hooks, `.gitattributes`/CRLF filters, GPG signing) is out of the current subset and throws `NotImplementedError`.',
    ],
  },
];

async function listFilesRecursive(dir) {
  const out = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const child = new URL(`${entry.name}${entry.isDirectory() ? '/' : ''}`, dir);
    if (entry.isDirectory()) out.push(...(await listFilesRecursive(child)));
    else if (entry.isFile() && entry.name.endsWith('.test.ts')) out.push(child);
  }
  return out;
}

function table(rows) {
  return [
    '| Feature | Status | Notes |',
    '|---|---|---|',
    ...rows.map(([feature, status, notes]) => `| ${feature} | ${status} | ${notes} |`),
  ].join('\n');
}

function bulletList(items) {
  return items.map((item) => `- ${item}`).join('\n');
}

function renderMatrix(matrix) {
  return `# ${matrix.title}

${generatedNote}

${matrix.intro}

${legend}

${table(matrix.rows)}

## Test Sources

${bulletList(matrix.tests)}

## Known Limitations

${bulletList(matrix.limitations)}
`;
}

function sourcePathFromRendered(rendered) {
  const match = /^`(.+)`$/.exec(rendered);
  if (!match) throw new Error(`compat source must be a backticked path: ${rendered}`);
  return match[1] ?? '';
}

async function sourceMatches(rendered) {
  const source = sourcePathFromRendered(rendered);
  if (!source.includes('*')) {
    const url = new URL(source, rootDir);
    try {
      if ((await stat(url)).isFile()) return [source];
    } catch {
      throw new Error(`compat source does not exist: ${source}`);
    }
    throw new Error(`compat source is not a file: ${source}`);
  }
  if (!source.endsWith('*.case.ts')) {
    throw new Error(`unsupported compat source glob: ${source}`);
  }
  const dir = new URL(source.slice(0, source.lastIndexOf('/') + 1), rootDir);
  const entries = await readdir(dir, { withFileTypes: true });
  const matches = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.case.ts'))
    .map((entry) => `${source.slice(0, source.lastIndexOf('/') + 1)}${entry.name}`);
  if (matches.length === 0) throw new Error(`compat source glob matched no files: ${source}`);
  return matches;
}

async function validateMatrixSources() {
  const seen = new Set();
  for (const matrix of matrices) {
    for (const source of matrix.tests) {
      for (const match of await sourceMatches(source)) seen.add(match);
    }
  }
  return seen.size;
}

function renderReadme() {
  return `# Compatibility matrices

These files are the public claim surface for rifty compatibility. Treat missing areas as
undocumented, not supported. The point is honest fit: tested support, visible caveats, and loud
unsupported rows.

Each markdown here cites the covering tests in \`tests/conformance/\` and \`tests/integration/\` for a
Node-compatible area. \`fs.md\`/\`streams.md\`/\`http.md\`/\`zlib.md\`/\`git.md\` are rendered by \`pnpm compat:generate\`
from static inventories whose cited test files are existence-checked, not re-run — deriving statuses
from test RESULTS is tracked in \`docs/backlog/toolchain-build/compat-matrix-test-result-sink\`.

- [modules.md](./modules.md) — M2 (Modules)
- [buffer.md](./buffer.md) — \`Buffer\` polyfill (\`@riftydev/io\`)
- [fs.md](./fs.md) — \`node:fs\` runtime VFS subset
- [streams.md](./streams.md) — \`node:stream\` subset
- [http.md](./http.md) — \`node:http\` / browser-local port registry subset
- [zlib.md](./zlib.md) — \`node:zlib\` web-compression-backed async subset (ADR-0159)
- [ts-language-service.md](./ts-language-service.md) — in-browser \`ts.LanguageService\` over the VFS (\`@riftydev/ts-language-service\`, ADR-0166)
- [package-tooling.md](./package-tooling.md) — real package CLIs in the browser shell (Prettier, ESLint, typed \`typescript-eslint\`)
- [git.md](./git.md) — git over the VFS (isomorphic-git, ADR-0167); offline-faithful porcelain + smart-HTTP network ceiling
- [vite-command.md](./vite-command.md) — playground \`vite\` command through the installed \`.bin\` CLI (ADR-0174)
- [process.md](./process.md) — process lifecycle / event-loop drain + the drain-cap divergence (ADR-0152); the terminal \`node <file>\` command + its gaps (ADR-0155/0157)
- [wasi.md](./wasi.md) — WASI preview1 syscall surface (\`@riftydev/runtime-wasi\`)
- [incompatible-packages.md](./incompatible-packages.md) — packages rifty can't run (native deps)
- (sqlite.md — coming with the \`node:sqlite\` \`DatabaseSync\` shim, ADR-0065)
- (browsers.md — coming with first cross-browser CI run)

${legend}
`;
}

await mkdir(matrixDir, { recursive: true });
const sourceCount = await validateMatrixSources();
await writeFile(new URL('README.md', matrixDir), renderReadme());
for (const matrix of matrices) {
  await writeFile(new URL(matrix.file, matrixDir), renderMatrix(matrix));
}

const tests = await listFilesRecursive(conformanceDir);
console.log(
  `compat-matrix-generator: wrote ${matrices.length} matrix doc(s); verified ${sourceCount} cited source file(s); scanned ${tests.length} conformance test file(s)`,
);
for (const matrix of matrices) console.log(`  doc: ${matrix.file}`);
